/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class AutorEliminarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AutorEliminarView
     */
    public AutorEliminarView() {
        initComponents();
    }
    
    private ResourceBundle bundle;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreAutorEliminar = new javax.swing.JLabel();
        lblYearAutorEliminar = new javax.swing.JLabel();
        lblNacionalidadAutorEliminar = new javax.swing.JLabel();
        txtNombreAutorEliminar = new javax.swing.JTextField();
        txtYearAutorEliminar = new javax.swing.JTextField();
        txtNacionalidadAutorEliminar = new javax.swing.JTextField();
        btnBuscarAutorEliminar = new javax.swing.JButton();
        btnLimpiarAutorEliminar = new javax.swing.JButton();
        btnEliminarAutorEliminar = new javax.swing.JButton();
        btnCancelarAutorEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(207, 162, 124));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblNombreAutorEliminar.setText("Nombre");

        lblYearAutorEliminar.setText("Año de nacimiento");

        lblNacionalidadAutorEliminar.setText("Nacionalidad");

        txtNombreAutorEliminar.addActionListener(this::txtNombreAutorEliminarActionPerformed);

        txtYearAutorEliminar.setEnabled(false);

        txtNacionalidadAutorEliminar.setEnabled(false);

        btnBuscarAutorEliminar.setText("Buscar");

        btnLimpiarAutorEliminar.setText("Limpiar");

        btnEliminarAutorEliminar.setText("Eliminar");

        btnCancelarAutorEliminar.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYearAutorEliminar)
                    .addComponent(lblNombreAutorEliminar)
                    .addComponent(lblNacionalidadAutorEliminar))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombreAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarAutorEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiarAutorEliminar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnEliminarAutorEliminar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                            .addComponent(btnCancelarAutorEliminar))
                        .addComponent(txtNacionalidadAutorEliminar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtYearAutorEliminar, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAutorEliminar)
                    .addComponent(txtNombreAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAutorEliminar)
                    .addComponent(btnLimpiarAutorEliminar))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYearAutorEliminar)
                    .addComponent(txtYearAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNacionalidadAutorEliminar)
                    .addComponent(txtNacionalidadAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarAutorEliminar)
                    .addComponent(btnCancelarAutorEliminar))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreAutorEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAutorEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAutorEliminarActionPerformed
    public JTextField getTxtNombre() {
        return txtNombreAutorEliminar;
    }

    public JTextField getTxtYear() {
        return txtYearAutorEliminar;
    }

    public JTextField getTxtNacionalidad() {
        return txtNacionalidadAutorEliminar;
    }

    public JButton getBtnBuscar() {
        return btnBuscarAutorEliminar;
    }

    public JButton getBtnEliminar() {
        return btnEliminarAutorEliminar;
    }

    public JButton getBtnCancelar() {
        return btnCancelarAutorEliminar;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiarAutorEliminar;
    }

    public void mostrarMensaje(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }

    public int mostrarConfirmacion(String llaveMensaje) {
        String mensaje = this.bundle.getString(llaveMensaje);
        return javax.swing.JOptionPane.showConfirmDialog(this, mensaje);
    }
    public void cambiarIdioma(Locale locale) {
        this.bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);
        
    lblNacionalidadAutorEliminar.setText(bundle.getString("autor.nacionalidad"));
    lblNombreAutorEliminar.setText(bundle.getString("usuario.nombre"));
    lblYearAutorEliminar.setText(bundle.getString("autor.anio"));

    btnBuscarAutorEliminar.setText(bundle.getString("boton.buscar"));
    btnEliminarAutorEliminar.setText(bundle.getString("boton.eliminar"));
    btnLimpiarAutorEliminar.setText(bundle.getString("boton.limpiar"));
    btnCancelarAutorEliminar.setText(bundle.getString("boton.cancelar"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAutorEliminar;
    private javax.swing.JButton btnCancelarAutorEliminar;
    private javax.swing.JButton btnEliminarAutorEliminar;
    private javax.swing.JButton btnLimpiarAutorEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNacionalidadAutorEliminar;
    private javax.swing.JLabel lblNombreAutorEliminar;
    private javax.swing.JLabel lblYearAutorEliminar;
    private javax.swing.JTextField txtNacionalidadAutorEliminar;
    private javax.swing.JTextField txtNombreAutorEliminar;
    private javax.swing.JTextField txtYearAutorEliminar;
    // End of variables declaration//GEN-END:variables
}
