/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import java.awt.event.ActionListener;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class AutorActualizarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AutorActualizarView
     */
    public AutorActualizarView() {
        initComponents();
    }

    private ResourceBundle bundle; // para poder cambiar el mensaje del metodo y no romper con el MVC

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreAutorActualizar = new javax.swing.JLabel();
        lblYearAutorActualizar = new javax.swing.JLabel();
        lblNacionalidadAutorActualizar = new javax.swing.JLabel();
        txtNombreAutorActualizar = new javax.swing.JTextField();
        txtYearAutorActualizar = new javax.swing.JTextField();
        txtNacionalidadAutorActualizar = new javax.swing.JTextField();
        btnBuscarAutorActualizar = new javax.swing.JButton();
        btnLimpiarAutorActualizar = new javax.swing.JButton();
        btnActualizarAutorActualizar = new javax.swing.JButton();
        btnCancelarAutorActualizar = new javax.swing.JButton();
        cbxNombreAutorActualizar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(207, 162, 124));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblNombreAutorActualizar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblNombreAutorActualizar.setText("Nombre");

        lblYearAutorActualizar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblYearAutorActualizar.setText("Año de nacimiento");

        lblNacionalidadAutorActualizar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblNacionalidadAutorActualizar.setText("Nacionalidad");

        txtNombreAutorActualizar.setEditable(false);
        txtNombreAutorActualizar.setEnabled(false);

        btnBuscarAutorActualizar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnBuscarAutorActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/LUPA_.png"))); // NOI18N
        btnBuscarAutorActualizar.setText("Buscar");

        btnLimpiarAutorActualizar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnLimpiarAutorActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/Escoba.png"))); // NOI18N
        btnLimpiarAutorActualizar.setText("Limpiar");

        btnActualizarAutorActualizar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnActualizarAutorActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/Actualizarcon.png"))); // NOI18N
        btnActualizarAutorActualizar.setText("Actualizar");

        btnCancelarAutorActualizar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnCancelarAutorActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/X-.png"))); // NOI18N
        btnCancelarAutorActualizar.setText("Cancelar");

        cbxNombreAutorActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxNombreAutorActualizar.addActionListener(this::cbxNombreAutorActualizarActionPerformed);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/Aactualizar-Photoroom.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreAutorActualizar)
                            .addComponent(lblYearAutorActualizar)
                            .addComponent(lblNacionalidadAutorActualizar))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNacionalidadAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtYearAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(130, 130, 130)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxNombreAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(btnBuscarAutorActualizar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLimpiarAutorActualizar))))
                            .addComponent(txtNombreAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnActualizarAutorActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarAutorActualizar)
                        .addGap(310, 310, 310)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxNombreAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreAutorActualizar))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYearAutorActualizar)
                            .addComponent(txtYearAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarAutorActualizar)
                            .addComponent(btnLimpiarAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNacionalidadAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNacionalidadAutorActualizar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnCancelarAutorActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnActualizarAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxNombreAutorActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNombreAutorActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNombreAutorActualizarActionPerformed

    public JTextField getTxtNombre() {
        return txtNombreAutorActualizar;
    }

    public JTextField getTxtYear() {
        return txtYearAutorActualizar;
    }

    public JTextField getTxtNacionalidad() {
        return txtNacionalidadAutorActualizar;
    }

    public JButton getBtnCancelar() {
        return btnCancelarAutorActualizar;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiarAutorActualizar;
    }

    public JButton getBtnActualizarAutorActualizar() {
        return btnActualizarAutorActualizar;
    }

    public JButton getBtnBuscarAutorActualizar() {
        return btnBuscarAutorActualizar;
    }

    public JComboBox<String> getCbxNombreAutorActualizar() {
        return cbxNombreAutorActualizar;
    }

    public void setCbxNombreAutorActualizar(JComboBox<String> cbxNombreAutorActualizar) {
        this.cbxNombreAutorActualizar = cbxNombreAutorActualizar;
    }
    

    public void cambiarIdioma(Locale locale) {
        this.bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);
        lblNacionalidadAutorActualizar.setText(bundle.getString("autor.nacionalidad"));
        lblNombreAutorActualizar.setText(bundle.getString("usuario.nombre"));
        lblYearAutorActualizar.setText(bundle.getString("autor.anio"));

        btnBuscarAutorActualizar.setText(bundle.getString("boton.buscar"));
        btnActualizarAutorActualizar.setText(bundle.getString("boton.actualizar"));
        btnLimpiarAutorActualizar.setText(bundle.getString("boton.limpiar"));
        btnCancelarAutorActualizar.setText(bundle.getString("boton.cancelar"));
    }

  public void mostrarMensaje(String llaveMensaje) {
    
    String mensaje = this.bundle.getString(llaveMensaje);

    javax.swing.JOptionPane.showMessageDialog(this, mensaje);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarAutorActualizar;
    private javax.swing.JButton btnBuscarAutorActualizar;
    private javax.swing.JButton btnCancelarAutorActualizar;
    private javax.swing.JButton btnLimpiarAutorActualizar;
    private javax.swing.JComboBox<String> cbxNombreAutorActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNacionalidadAutorActualizar;
    private javax.swing.JLabel lblNombreAutorActualizar;
    private javax.swing.JLabel lblYearAutorActualizar;
    private javax.swing.JTextField txtNacionalidadAutorActualizar;
    private javax.swing.JTextField txtNombreAutorActualizar;
    private javax.swing.JTextField txtYearAutorActualizar;
    // End of variables declaration//GEN-END:variables
}
