/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import java.awt.event.ActionListener;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class AutorCrearView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AutorCrearView
     */
    public AutorCrearView() {
        initComponents();
    }
    
    private ResourceBundle bundle;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreAutorCrear = new javax.swing.JLabel();
        lblYearAutorCrear = new javax.swing.JLabel();
        lblNacionalidadAutorCrear = new javax.swing.JLabel();
        txtNombreAutorCrear = new javax.swing.JTextField();
        txtYearAutorCrear = new javax.swing.JTextField();
        txtNacionalidadAutorCrear = new javax.swing.JTextField();
        btnCrearAutorCrear = new javax.swing.JButton();
        btnCancelarAutorCrear = new javax.swing.JButton();
        btnLimpiarAutorCrear = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(207, 162, 124));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblNombreAutorCrear.setText("Nombre");

        lblYearAutorCrear.setText("Año de Nacimiento");

        lblNacionalidadAutorCrear.setText("Nacionalidad");

        btnCrearAutorCrear.setText("Crear");

        btnCancelarAutorCrear.setText("Cancelar");

        btnLimpiarAutorCrear.setText("Limpiar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNacionalidadAutorCrear)
                    .addComponent(lblYearAutorCrear)
                    .addComponent(lblNombreAutorCrear))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCrearAutorCrear)
                        .addGap(33, 33, 33)
                        .addComponent(btnCancelarAutorCrear)
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNombreAutorCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                        .addComponent(txtYearAutorCrear)
                        .addComponent(txtNacionalidadAutorCrear)))
                .addGap(54, 54, 54)
                .addComponent(btnLimpiarAutorCrear)
                .addGap(0, 85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreAutorCrear)
                    .addComponent(txtNombreAutorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYearAutorCrear)
                    .addComponent(txtYearAutorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarAutorCrear))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNacionalidadAutorCrear)
                    .addComponent(txtNacionalidadAutorCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarAutorCrear)
                    .addComponent(btnCrearAutorCrear))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public JTextField getTxtNombre() {
        return txtNombreAutorCrear;
    }

    public JTextField getTxtYear() {
        return txtYearAutorCrear;
    }

    public JTextField getTxtNacionalidad() {
        return txtNacionalidadAutorCrear;
    }

    public JButton getBtnCrear() {
        return btnCrearAutorCrear;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiarAutorCrear;
    }

    public JButton getBtnCancelar() {
        return btnCancelarAutorCrear;
    }

    public void cambiarIdioma(Locale locale) {
        this.bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);

        lblNacionalidadAutorCrear.setText(bundle.getString("autor.nacionalidad"));
        lblNombreAutorCrear.setText(bundle.getString("usuario.nombre"));
        lblYearAutorCrear.setText(bundle.getString("autor.anio"));

        btnCrearAutorCrear.setText(bundle.getString("boton.crear"));
        btnLimpiarAutorCrear.setText(bundle.getString("boton.limpiar"));
        btnCancelarAutorCrear.setText(bundle.getString("boton.cancelar"));
    }

    public void mostrarMensaje(String llaveMensaje) {

        String mensaje = this.bundle.getString(llaveMensaje);

        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarAutorCrear;
    private javax.swing.JButton btnCrearAutorCrear;
    private javax.swing.JButton btnLimpiarAutorCrear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNacionalidadAutorCrear;
    private javax.swing.JLabel lblNombreAutorCrear;
    private javax.swing.JLabel lblYearAutorCrear;
    private javax.swing.JTextField txtNacionalidadAutorCrear;
    private javax.swing.JTextField txtNombreAutorCrear;
    private javax.swing.JTextField txtYearAutorCrear;
    // End of variables declaration//GEN-END:variables
}
