/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class AutorEliminarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AutorEliminarView
     */
    public AutorEliminarView() {
        initComponents();
    }
    
    private ResourceBundle bundle;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreAutorEliminar = new javax.swing.JLabel();
        lblYearAutorEliminar = new javax.swing.JLabel();
        lblNacionalidadAutorEliminar = new javax.swing.JLabel();
        txtNombreAutorEliminar = new javax.swing.JTextField();
        txtYearAutorEliminar = new javax.swing.JTextField();
        txtNacionalidadAutorEliminar = new javax.swing.JTextField();
        btnBuscarAutorEliminar = new javax.swing.JButton();
        btnLimpiarAutorEliminar = new javax.swing.JButton();
        btnEliminarAutorEliminar = new javax.swing.JButton();
        btnCancelarAutorEliminar = new javax.swing.JButton();
        cbxNombreAutorEliminar = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(207, 162, 124));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblNombreAutorEliminar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblNombreAutorEliminar.setText("Nombre");

        lblYearAutorEliminar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblYearAutorEliminar.setText("Año de nacimiento");

        lblNacionalidadAutorEliminar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblNacionalidadAutorEliminar.setText("Nacionalidad");

        txtNombreAutorEliminar.addActionListener(this::txtNombreAutorEliminarActionPerformed);

        txtYearAutorEliminar.setEnabled(false);

        txtNacionalidadAutorEliminar.setEnabled(false);

        btnBuscarAutorEliminar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnBuscarAutorEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/LUPA_.png"))); // NOI18N
        btnBuscarAutorEliminar.setText("Buscar");

        btnLimpiarAutorEliminar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnLimpiarAutorEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/Escoba.png"))); // NOI18N
        btnLimpiarAutorEliminar.setText("Limpiar");

        btnEliminarAutorEliminar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnEliminarAutorEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/eliminar.png"))); // NOI18N
        btnEliminarAutorEliminar.setText("Eliminar");

        btnCancelarAutorEliminar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnCancelarAutorEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/X-.png"))); // NOI18N
        btnCancelarAutorEliminar.setText("Cancelar");

        cbxNombreAutorEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/image-Photoroom.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(89, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombreAutorEliminar)
                                    .addComponent(lblNacionalidadAutorEliminar))
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblYearAutorEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtNacionalidadAutorEliminar, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtYearAutorEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNombreAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxNombreAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnBuscarAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnLimpiarAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(btnEliminarAutorEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarAutorEliminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxNombreAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtYearAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblYearAutorEliminar))
                            .addComponent(btnBuscarAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimpiarAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNacionalidadAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNacionalidadAutorEliminar)))
                    .addComponent(lblNombreAutorEliminar))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreAutorEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAutorEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAutorEliminarActionPerformed
    public JTextField getTxtNombre() {
        return txtNombreAutorEliminar;
    }

    public JTextField getTxtYear() {
        return txtYearAutorEliminar;
    }

    public JTextField getTxtNacionalidad() {
        return txtNacionalidadAutorEliminar;
    }

    public JButton getBtnBuscar() {
        return btnBuscarAutorEliminar;
    }

    public JButton getBtnEliminar() {
        return btnEliminarAutorEliminar;
    }

    public JButton getBtnCancelar() {
        return btnCancelarAutorEliminar;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiarAutorEliminar;
    }

    public JComboBox<String> getCbxNombreAutorEliminar() {
        return cbxNombreAutorEliminar;
    }

    public void setCbxNombreAutorEliminar(JComboBox<String> cbxNombreAutorEliminar) {
        this.cbxNombreAutorEliminar = cbxNombreAutorEliminar;
    }
    

    public void mostrarMensaje(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }

    public int mostrarConfirmacion(String llaveMensaje) {
        String mensaje = this.bundle.getString(llaveMensaje);
        return javax.swing.JOptionPane.showConfirmDialog(this, mensaje);
    }
    public void cambiarIdioma(Locale locale) {
        this.bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);
        
    lblNacionalidadAutorEliminar.setText(bundle.getString("autor.nacionalidad"));
    lblNombreAutorEliminar.setText(bundle.getString("usuario.nombre"));
    lblYearAutorEliminar.setText(bundle.getString("autor.anio"));

    btnBuscarAutorEliminar.setText(bundle.getString("boton.buscar"));
    btnEliminarAutorEliminar.setText(bundle.getString("boton.eliminar"));
    btnLimpiarAutorEliminar.setText(bundle.getString("boton.limpiar"));
    btnCancelarAutorEliminar.setText(bundle.getString("boton.cancelar"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAutorEliminar;
    private javax.swing.JButton btnCancelarAutorEliminar;
    private javax.swing.JButton btnEliminarAutorEliminar;
    private javax.swing.JButton btnLimpiarAutorEliminar;
    private javax.swing.JComboBox<String> cbxNombreAutorEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNacionalidadAutorEliminar;
    private javax.swing.JLabel lblNombreAutorEliminar;
    private javax.swing.JLabel lblYearAutorEliminar;
    private javax.swing.JTextField txtNacionalidadAutorEliminar;
    private javax.swing.JTextField txtNombreAutorEliminar;
    private javax.swing.JTextField txtYearAutorEliminar;
    // End of variables declaration//GEN-END:variables
}
