/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class AutorActualizarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form AutorActualizarView
     */
    public AutorActualizarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreAutorActualizar = new javax.swing.JLabel();
        lblYearAutorActualizar = new javax.swing.JLabel();
        lblNacionalidadAutorActualizar = new javax.swing.JLabel();
        txtNombreAutorActualizar = new javax.swing.JTextField();
        txtYearAutorActualizar = new javax.swing.JTextField();
        txtNacionalidadAutorActualizar = new javax.swing.JTextField();
        btnBuscarAutorActualizar = new javax.swing.JButton();
        btnLimpiarAutorActualizar = new javax.swing.JButton();
        btnActualizarAutorActualizar = new javax.swing.JButton();
        btnCancelarAutorActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(207, 162, 124));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblNombreAutorActualizar.setText("Nombre");

        lblYearAutorActualizar.setText("Año de nacimiento");

        lblNacionalidadAutorActualizar.setText("Nacionalidad");

        btnBuscarAutorActualizar.setText("Buscar");

        btnLimpiarAutorActualizar.setText("Limpiar");

        btnActualizarAutorActualizar.setText("Actualizar");

        btnCancelarAutorActualizar.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreAutorActualizar)
                    .addComponent(lblYearAutorActualizar)
                    .addComponent(lblNacionalidadAutorActualizar))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNombreAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnBuscarAutorActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiarAutorActualizar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnActualizarAutorActualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                            .addComponent(btnCancelarAutorActualizar))
                        .addComponent(txtNacionalidadAutorActualizar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtYearAutorActualizar, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAutorActualizar)
                    .addComponent(txtNombreAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAutorActualizar)
                    .addComponent(btnLimpiarAutorActualizar))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblYearAutorActualizar)
                    .addComponent(txtYearAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNacionalidadAutorActualizar)
                    .addComponent(txtNacionalidadAutorActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarAutorActualizar)
                    .addComponent(btnCancelarAutorActualizar))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getTxtNombre() {
        return txtNombreAutorActualizar;
    }

    public JTextField getTxtYear() {
        return txtYearAutorActualizar;
    }

    public JTextField getTxtNacionalidad() {
        return txtNacionalidadAutorActualizar;
    }

    public JButton getBtnCancelar() {
        return btnCancelarAutorActualizar;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiarAutorActualizar;
    }

    public JButton getBtnActualizarAutorActualizar() {
        return btnActualizarAutorActualizar;
    }

    public JButton getBtnBuscarAutorActualizar() {
        return btnBuscarAutorActualizar;
    }

    public void mostrarMensaje(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarAutorActualizar;
    private javax.swing.JButton btnBuscarAutorActualizar;
    private javax.swing.JButton btnCancelarAutorActualizar;
    private javax.swing.JButton btnLimpiarAutorActualizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNacionalidadAutorActualizar;
    private javax.swing.JLabel lblNombreAutorActualizar;
    private javax.swing.JLabel lblYearAutorActualizar;
    private javax.swing.JTextField txtNacionalidadAutorActualizar;
    private javax.swing.JTextField txtNombreAutorActualizar;
    private javax.swing.JTextField txtYearAutorActualizar;
    // End of variables declaration//GEN-END:variables
}
