/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class LibroCrearView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearLibroView
     */
    public LibroCrearView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        panelLibroCrear = new javax.swing.JPanel();
        lblIsbnLibroCrear = new javax.swing.JLabel();
        txtIsbnLibroCrear = new javax.swing.JTextField();
        lblTituloLibroCrear = new javax.swing.JLabel();
        lblYearLibroCrear = new javax.swing.JLabel();
        lblGeneroLibroCrear = new javax.swing.JLabel();
        lblEditorialLibroCrear = new javax.swing.JLabel();
        txtTituloLibroCrear = new javax.swing.JTextField();
        txtYearLibroCrear = new javax.swing.JTextField();
        txtGeneroLibroCrear = new javax.swing.JTextField();
        txtEditorialLibroCrear = new javax.swing.JTextField();
        btnCrearLibroCrear = new javax.swing.JButton();
        btnCancelarLibroCrear = new javax.swing.JButton();
        lblAutorLibroCrear = new javax.swing.JLabel();
        lblDisponibleLibroCrear = new javax.swing.JLabel();
        txtAutorLibroCrear = new javax.swing.JTextField();
        rbtnDisponibleLibroCrear = new javax.swing.JRadioButton();
        btnLimpiarLibroCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        panelLibroCrear.setBackground(new java.awt.Color(255, 255, 255));

        lblIsbnLibroCrear.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblIsbnLibroCrear.setText("ISBN");

        txtIsbnLibroCrear.addActionListener(this::txtIsbnLibroCrearActionPerformed);

        lblTituloLibroCrear.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblTituloLibroCrear.setText("Titulo");

        lblYearLibroCrear.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblYearLibroCrear.setText("Año de publicación");

        lblGeneroLibroCrear.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblGeneroLibroCrear.setText("Género");

        lblEditorialLibroCrear.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblEditorialLibroCrear.setText("Editorial");

        txtTituloLibroCrear.addActionListener(this::txtTituloLibroCrearActionPerformed);

        btnCrearLibroCrear.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCrearLibroCrear.setText("Crear");
        btnCrearLibroCrear.addActionListener(this::btnCrearLibroCrearActionPerformed);

        btnCancelarLibroCrear.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCancelarLibroCrear.setText("Cancelar");

        lblAutorLibroCrear.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblAutorLibroCrear.setText("Autor");

        lblDisponibleLibroCrear.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        lblDisponibleLibroCrear.setText("Disponible");

        rbtnDisponibleLibroCrear.addActionListener(this::rbtnDisponibleLibroCrearActionPerformed);

        btnLimpiarLibroCrear.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLimpiarLibroCrear.setText("Limpiar");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/crearLibro.png"))); // NOI18N

        javax.swing.GroupLayout panelLibroCrearLayout = new javax.swing.GroupLayout(panelLibroCrear);
        panelLibroCrear.setLayout(panelLibroCrearLayout);
        panelLibroCrearLayout.setHorizontalGroup(
            panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibroCrearLayout.createSequentialGroup()
                .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLibroCrearLayout.createSequentialGroup()
                        .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLibroCrearLayout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(lblDisponibleLibroCrear)
                                .addGap(65, 65, 65)
                                .addComponent(rbtnDisponibleLibroCrear))
                            .addGroup(panelLibroCrearLayout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(btnCrearLibroCrear)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelarLibroCrear)
                                .addGap(30, 30, 30)
                                .addComponent(btnLimpiarLibroCrear)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelLibroCrearLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibroCrearLayout.createSequentialGroup()
                                .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIsbnLibroCrear)
                                    .addComponent(lblTituloLibroCrear))
                                .addGap(90, 90, 90))
                            .addGroup(panelLibroCrearLayout.createSequentialGroup()
                                .addComponent(lblEditorialLibroCrear)
                                .addGap(78, 78, 78)))
                        .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEditorialLibroCrear)
                            .addComponent(txtIsbnLibroCrear, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTituloLibroCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYearLibroCrear)
                            .addComponent(lblGeneroLibroCrear)
                            .addComponent(lblAutorLibroCrear))
                        .addGap(18, 18, 18)
                        .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtYearLibroCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(txtGeneroLibroCrear)
                            .addComponent(txtAutorLibroCrear))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibroCrearLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(222, 222, 222))
        );
        panelLibroCrearLayout.setVerticalGroup(
            panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibroCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLibroCrearLayout.createSequentialGroup()
                        .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIsbnLibroCrear)
                            .addComponent(txtIsbnLibroCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTituloLibroCrear)
                            .addComponent(txtTituloLibroCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLibroCrearLayout.createSequentialGroup()
                        .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblYearLibroCrear)
                            .addComponent(txtYearLibroCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGeneroLibroCrear)
                            .addComponent(txtGeneroLibroCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEditorialLibroCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAutorLibroCrear)
                        .addComponent(txtAutorLibroCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblEditorialLibroCrear))
                .addGap(28, 28, 28)
                .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisponibleLibroCrear)
                    .addComponent(rbtnDisponibleLibroCrear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(panelLibroCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearLibroCrear)
                    .addComponent(btnCancelarLibroCrear)
                    .addComponent(btnLimpiarLibroCrear))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLibroCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLibroCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIsbnLibroCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnLibroCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsbnLibroCrearActionPerformed

    private void txtTituloLibroCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloLibroCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloLibroCrearActionPerformed

    private void btnCrearLibroCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearLibroCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearLibroCrearActionPerformed

    private void rbtnDisponibleLibroCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDisponibleLibroCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDisponibleLibroCrearActionPerformed

    public JButton getBtnCancelarLibroCrear() {
        return btnCancelarLibroCrear;
    }

    public void setBtnCancelarLibroCrear(JButton btnCancelarLibroCrear) {
        this.btnCancelarLibroCrear = btnCancelarLibroCrear;
    }

    public JButton getBtnCrearLibroCrear() {
        return btnCrearLibroCrear;
    }

    public void setBtnCrearLibroCrear(JButton btnCrearLibroCrear) {
        this.btnCrearLibroCrear = btnCrearLibroCrear;
    }

    public JButton getBtnLimpiarLibroCrear() {
        return btnLimpiarLibroCrear;
    }

    public void setBtnLimpiarLibroCrear(JButton btnLimpiarLibroCrear) {
        this.btnLimpiarLibroCrear = btnLimpiarLibroCrear;
    }

    public JRadioButton getRbtnDisponibleLibroCrear() {
        return rbtnDisponibleLibroCrear;
    }

    public void setRbtnDisponibleLibroCrear(JRadioButton rbtnDisponibleLibroCrear) {
        this.rbtnDisponibleLibroCrear = rbtnDisponibleLibroCrear;
    }

    public JTextField getTxtAutorLibroCrear() {
        return txtAutorLibroCrear;
    }

    public void setTxtAutorLibroCrear(JTextField txtAutorLibroCrear) {
        this.txtAutorLibroCrear = txtAutorLibroCrear;
    }

    public JTextField getTxtEditorialLibroCrear() {
        return txtEditorialLibroCrear;
    }

    public void setTxtEditorialLibroCrear(JTextField txtEditorialLibroCrear) {
        this.txtEditorialLibroCrear = txtEditorialLibroCrear;
    }

    public JTextField getTxtGeneroLibroCrear() {
        return txtGeneroLibroCrear;
    }

    public void setTxtGeneroLibroCrear(JTextField txtGeneroLibroCrear) {
        this.txtGeneroLibroCrear = txtGeneroLibroCrear;
    }

    public JTextField getTxtIsbnLibroCrear() {
        return txtIsbnLibroCrear;
    }

    public void setTxtIsbnLibroCrear(JTextField txtIsbnLibroCrear) {
        this.txtIsbnLibroCrear = txtIsbnLibroCrear;
    }

    public JTextField getTxtTituloLibroCrear() {
        return txtTituloLibroCrear;
    }

    public void setTxtTituloLibroCrear(JTextField txtTituloLibroCrear) {
        this.txtTituloLibroCrear = txtTituloLibroCrear;
    }

    public JTextField getTxtYearLibroCrear() {
        return txtYearLibroCrear;
    }

    public void setTxtYearLibroCrear(JTextField txtYearLibroCrear) {
        this.txtYearLibroCrear = txtYearLibroCrear;
    }
    
           
    
    public void mostarMensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarLibroCrear;
    private javax.swing.JButton btnCrearLibroCrear;
    private javax.swing.JButton btnLimpiarLibroCrear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAutorLibroCrear;
    private javax.swing.JLabel lblDisponibleLibroCrear;
    private javax.swing.JLabel lblEditorialLibroCrear;
    private javax.swing.JLabel lblGeneroLibroCrear;
    private javax.swing.JLabel lblIsbnLibroCrear;
    private javax.swing.JLabel lblTituloLibroCrear;
    private javax.swing.JLabel lblYearLibroCrear;
    private javax.swing.JPanel panelLibroCrear;
    private javax.swing.JRadioButton rbtnDisponibleLibroCrear;
    private javax.swing.JTextField txtAutorLibroCrear;
    private javax.swing.JTextField txtEditorialLibroCrear;
    private javax.swing.JTextField txtGeneroLibroCrear;
    private javax.swing.JTextField txtIsbnLibroCrear;
    private javax.swing.JTextField txtTituloLibroCrear;
    private javax.swing.JTextField txtYearLibroCrear;
    // End of variables declaration//GEN-END:variables
}
