/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class LibroEliminarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarLibroView
     */
    public LibroEliminarView() {
        initComponents();
    }
    
    public void cambiarIdioma(Locale locale) {
        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);
        
    lblIsbnLibroEliminar.setText(bundle.getString("libro.isbn"));
    lblTituloLibroEliminar.setText(bundle.getString("libro.titulo"));
    lblAutorLibroEliminar.setText(bundle.getString("libro.autor"));
    lblEditorialLibroEliminar.setText(bundle.getString("libro.editorial"));
    lblGeneroLibroEliminar.setText(bundle.getString("libro.genero"));
    lblDisponibleLibroEliminar.setText(bundle.getString("libro.disponible"));
    lblYearLibroEliminar.setText(bundle.getString("libro.anio"));

    btnCrearLibroBuscar.setText(bundle.getString("boton.buscar"));
    btnEliminarLibroEliminar.setText(bundle.getString("boton.eliminar"));
    btnLimpiarLibroEliminar.setText(bundle.getString("boton.limpiar"));
    btnCancelarLibroEliminar.setText(bundle.getString("boton.cancelar"));

    rbtnDisponibleLibroEliminar.setText(bundle.getString("libro.disponible"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLibroBuscar = new javax.swing.JPanel();
        lblIsbnLibroEliminar = new javax.swing.JLabel();
        txtIsbnLibroEliminar = new javax.swing.JTextField();
        lblTituloLibroEliminar = new javax.swing.JLabel();
        lblYearLibroEliminar = new javax.swing.JLabel();
        lblGeneroLibroEliminar = new javax.swing.JLabel();
        lblEditorialLibroEliminar = new javax.swing.JLabel();
        txtTituloLibroEliminar = new javax.swing.JTextField();
        txtYearLibroEliminar = new javax.swing.JTextField();
        txtGeneroLibroEliminar = new javax.swing.JTextField();
        txtEditorialLibroEliminar = new javax.swing.JTextField();
        btnCrearLibroBuscar = new javax.swing.JButton();
        btnCancelarLibroEliminar = new javax.swing.JButton();
        lblAutorLibroEliminar = new javax.swing.JLabel();
        lblDisponibleLibroEliminar = new javax.swing.JLabel();
        txtAutorLibroEliminar = new javax.swing.JTextField();
        rbtnDisponibleLibroEliminar = new javax.swing.JRadioButton();
        btnLimpiarLibroEliminar = new javax.swing.JButton();
        btnEliminarLibroEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        panelLibroBuscar.setBackground(new java.awt.Color(204, 255, 255));

        lblIsbnLibroEliminar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblIsbnLibroEliminar.setText("ISBN");

        txtIsbnLibroEliminar.addActionListener(this::txtIsbnLibroEliminarActionPerformed);

        lblTituloLibroEliminar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblTituloLibroEliminar.setText("Titulo");

        lblYearLibroEliminar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblYearLibroEliminar.setText("Año de publicación");

        lblGeneroLibroEliminar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblGeneroLibroEliminar.setText("Género");

        lblEditorialLibroEliminar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblEditorialLibroEliminar.setText("Editorial");

        txtTituloLibroEliminar.setEnabled(false);
        txtTituloLibroEliminar.addActionListener(this::txtTituloLibroEliminarActionPerformed);

        txtYearLibroEliminar.setEnabled(false);
        txtYearLibroEliminar.addActionListener(this::txtYearLibroEliminarActionPerformed);

        txtGeneroLibroEliminar.setEnabled(false);

        txtEditorialLibroEliminar.setEnabled(false);

        btnCrearLibroBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/LUPA_.png"))); // NOI18N
        btnCrearLibroBuscar.setText("Buscar");
        btnCrearLibroBuscar.addActionListener(this::btnCrearLibroBuscarActionPerformed);

        btnCancelarLibroEliminar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCancelarLibroEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/X.png"))); // NOI18N
        btnCancelarLibroEliminar.setText("Cancelar");

        lblAutorLibroEliminar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblAutorLibroEliminar.setText("Autor");

        lblDisponibleLibroEliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblDisponibleLibroEliminar.setText("Disponible");

        txtAutorLibroEliminar.setEnabled(false);

        rbtnDisponibleLibroEliminar.setEnabled(false);

        btnLimpiarLibroEliminar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLimpiarLibroEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/Escoba.png"))); // NOI18N
        btnLimpiarLibroEliminar.setText("Limpiar");
        btnLimpiarLibroEliminar.addActionListener(this::btnLimpiarLibroEliminarActionPerformed);

        btnEliminarLibroEliminar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEliminarLibroEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/eliminar.png"))); // NOI18N
        btnEliminarLibroEliminar.setText("Eliminar");
        btnEliminarLibroEliminar.addActionListener(this::btnEliminarLibroEliminarActionPerformed);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/eliminarLibro.png"))); // NOI18N

        javax.swing.GroupLayout panelLibroBuscarLayout = new javax.swing.GroupLayout(panelLibroBuscar);
        panelLibroBuscar.setLayout(panelLibroBuscarLayout);
        panelLibroBuscarLayout.setHorizontalGroup(
            panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibroBuscarLayout.createSequentialGroup()
                        .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                                        .addComponent(lblIsbnLibroEliminar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtIsbnLibroEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibroBuscarLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnCrearLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)))
                                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                                            .addComponent(lblAutorLibroEliminar)
                                            .addGap(103, 103, 103))
                                        .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                                            .addComponent(lblYearLibroEliminar)
                                            .addGap(18, 18, 18)))
                                    .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                                        .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTituloLibroEliminar)
                                            .addComponent(lblGeneroLibroEliminar)
                                            .addComponent(lblEditorialLibroEliminar))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblDisponibleLibroEliminar)
                                .addGap(65, 65, 65)
                                .addComponent(rbtnDisponibleLibroEliminar)
                                .addGap(18, 18, 18)))
                        .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditorialLibroEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                            .addComponent(txtYearLibroEliminar)
                            .addComponent(txtGeneroLibroEliminar)
                            .addComponent(txtAutorLibroEliminar)
                            .addComponent(txtTituloLibroEliminar))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibroBuscarLayout.createSequentialGroup()
                        .addGap(0, 79, Short.MAX_VALUE)
                        .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibroBuscarLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(215, 215, 215))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibroBuscarLayout.createSequentialGroup()
                                .addComponent(btnEliminarLibroEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelarLibroEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiarLibroEliminar)
                                .addGap(178, 178, 178))))))
        );
        panelLibroBuscarLayout.setVerticalGroup(
            panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTituloLibroEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTituloLibroEliminar))
                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(txtEditorialLibroEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAutorLibroEliminar)
                            .addComponent(txtAutorLibroEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDisponibleLibroEliminar)
                            .addComponent(rbtnDisponibleLibroEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelarLibroEliminar)
                            .addComponent(btnLimpiarLibroEliminar)
                            .addComponent(btnEliminarLibroEliminar))
                        .addGap(19, 19, 19))
                    .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                        .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtYearLibroEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYearLibroEliminar)
                            .addComponent(lblIsbnLibroEliminar)
                            .addComponent(txtIsbnLibroEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtGeneroLibroEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGeneroLibroEliminar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblEditorialLibroEliminar))
                            .addComponent(btnCrearLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLibroBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLibroBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIsbnLibroEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnLibroEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsbnLibroEliminarActionPerformed

    private void txtTituloLibroEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloLibroEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloLibroEliminarActionPerformed

    private void btnCrearLibroBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearLibroBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearLibroBuscarActionPerformed

    private void btnEliminarLibroEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLibroEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarLibroEliminarActionPerformed

    private void btnLimpiarLibroEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarLibroEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarLibroEliminarActionPerformed

    private void txtYearLibroEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearLibroEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearLibroEliminarActionPerformed

    public JButton getBtnLimpiarLibroEliminar() {
        return btnLimpiarLibroEliminar;
    }

    
    public JButton getBtnCancelarLibroEliminar() {
        return btnCancelarLibroEliminar;
    }

    public JButton getBtnCrearLibroBuscar() {
        return btnCrearLibroBuscar;
    }

    public JButton getBtnEliminarLibroEliminar() {
        return btnEliminarLibroEliminar;
    }

    public JRadioButton getRbtnDisponibleLibroEliminar() {
        return rbtnDisponibleLibroEliminar;
    }

    public JTextField getTxtAutorLibroEliminar() {
        return txtAutorLibroEliminar;
    }

    public JTextField getTxtEditorialLibroEliminar() {
        return txtEditorialLibroEliminar;
    }

    public JTextField getTxtGeneroLibroEliminar() {
        return txtGeneroLibroEliminar;
    }

    public JTextField getTxtIsbnLibroEliminar() {
        return txtIsbnLibroEliminar;
    }

    public JTextField getTxtTituloLibroEliminar() {
        return txtTituloLibroEliminar;
    }

    public JTextField getTxtYearLibroEliminar() {
        return txtYearLibroEliminar;
    }

    public int mostarMensaje(String mensaje){
        return JOptionPane.showConfirmDialog(this, mensaje);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarLibroEliminar;
    private javax.swing.JButton btnCrearLibroBuscar;
    private javax.swing.JButton btnEliminarLibroEliminar;
    private javax.swing.JButton btnLimpiarLibroEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAutorLibroEliminar;
    private javax.swing.JLabel lblDisponibleLibroEliminar;
    private javax.swing.JLabel lblEditorialLibroEliminar;
    private javax.swing.JLabel lblGeneroLibroEliminar;
    private javax.swing.JLabel lblIsbnLibroEliminar;
    private javax.swing.JLabel lblTituloLibroEliminar;
    private javax.swing.JLabel lblYearLibroEliminar;
    private javax.swing.JPanel panelLibroBuscar;
    private javax.swing.JRadioButton rbtnDisponibleLibroEliminar;
    private javax.swing.JTextField txtAutorLibroEliminar;
    private javax.swing.JTextField txtEditorialLibroEliminar;
    private javax.swing.JTextField txtGeneroLibroEliminar;
    private javax.swing.JTextField txtIsbnLibroEliminar;
    private javax.swing.JTextField txtTituloLibroEliminar;
    private javax.swing.JTextField txtYearLibroEliminar;
    // End of variables declaration//GEN-END:variables
}
