/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import ec.edu.ups.biblioteca.models.Libro;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class LibroListarView extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo;

    /**
     * Creates new form LibroListarView
     */
    public LibroListarView() {
        initComponents();
        ConfigurarTabla();
    }
    
    public void ConfigurarTabla(){
    modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    
    modelo.addColumn("ISBN");
    modelo.addColumn("Titulo");
    modelo.addColumn("Año de publicación");
    modelo.addColumn("Género");
    modelo.addColumn("Editorial");
    modelo.addColumn("Autor");
    modelo.addColumn("Disponible");
    
    tblListarLibro.setModel(modelo); 

    tblListarLibro.getTableHeader().setReorderingAllowed(false);
    tblListarLibro.getTableHeader().setResizingAllowed(false);
}
    
    public void cargarDatos(List<Libro> libros){
        
        modelo.setRowCount(0);
        
        for(Libro libro : libros){
            Object[] fila = {libro.getIsbn(),libro.getTitulo(),libro.getAñoDePublicacion(),libro.getGenero(),libro.getEditorial(),libro.getAutor(),libro.isDisponible()};
            modelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListarLibro = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblListarLibro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblListarLibro.setEnabled(false);
        jScrollPane1.setViewportView(tblListarLibro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListarLibro;
    // End of variables declaration//GEN-END:variables
}
