/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class LibroActualizarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form LibroActualizarView
     */
    public LibroActualizarView() {
        initComponents();
    }
    
    public void cambiarIdioma(Locale locale) {
        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);
        
    lblIsbnLibroActualizar.setText(bundle.getString("libro.isbn"));
    lblTituloLibroActualizar.setText(bundle.getString("libro.titulo"));
    lblAutorLibroActualizar.setText(bundle.getString("libro.autor"));
    lblEditorialLibroActualizar.setText(bundle.getString("libro.editorial"));
    lblGeneroLibroActualizar.setText(bundle.getString("libro.genero"));
    lblDisponibleLibroActualizar.setText(bundle.getString("libro.disponible"));
    lblYearLibroActualizar.setText(bundle.getString("libro.anio"));

    btnBuscarLibroActualizar.setText(bundle.getString("boton.buscar"));
    btnActualizarLibroActualizar.setText(bundle.getString("boton.actualizar"));
    btnLimpiarLibroActualizar.setText(bundle.getString("boton.limpiar"));
    btnCancelarLibroActualizar.setText(bundle.getString("boton.cancelar"));

    rbtnDisponibleLibroActualizar.setText(bundle.getString("libro.disponible"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLibroActualizar = new javax.swing.JPanel();
        lblIsbnLibroActualizar = new javax.swing.JLabel();
        txtIsbnLibroActualizar = new javax.swing.JTextField();
        lblTituloLibroActualizar = new javax.swing.JLabel();
        lblYearLibroActualizar = new javax.swing.JLabel();
        lblGeneroLibroActualizar = new javax.swing.JLabel();
        lblEditorialLibroActualizar = new javax.swing.JLabel();
        txtTituloLibroActualizar = new javax.swing.JTextField();
        txtYearLibroActualizar = new javax.swing.JTextField();
        txtGeneroLibroActualizar = new javax.swing.JTextField();
        txtEditorialLibroActualizar = new javax.swing.JTextField();
        btnActualizarLibroActualizar = new javax.swing.JButton();
        btnCancelarLibroActualizar = new javax.swing.JButton();
        lblAutorLibroActualizar = new javax.swing.JLabel();
        lblDisponibleLibroActualizar = new javax.swing.JLabel();
        txtAutorLibroActualizar = new javax.swing.JTextField();
        rbtnDisponibleLibroActualizar = new javax.swing.JRadioButton();
        btnBuscarLibroActualizar = new javax.swing.JButton();
        btnLimpiarLibroActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        panelLibroActualizar.setBackground(new java.awt.Color(255, 255, 255));

        lblIsbnLibroActualizar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblIsbnLibroActualizar.setText("ISBN");

        txtIsbnLibroActualizar.addActionListener(this::txtIsbnLibroActualizarActionPerformed);

        lblTituloLibroActualizar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblTituloLibroActualizar.setText("Titulo");

        lblYearLibroActualizar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblYearLibroActualizar.setText("Año de publicación");

        lblGeneroLibroActualizar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblGeneroLibroActualizar.setText("Género");

        lblEditorialLibroActualizar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblEditorialLibroActualizar.setText("Editorial");

        txtTituloLibroActualizar.addActionListener(this::txtTituloLibroActualizarActionPerformed);

        txtYearLibroActualizar.addActionListener(this::txtYearLibroActualizarActionPerformed);

        btnActualizarLibroActualizar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnActualizarLibroActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/actualizar.png"))); // NOI18N
        btnActualizarLibroActualizar.setText("Actualizar");
        btnActualizarLibroActualizar.addActionListener(this::btnActualizarLibroActualizarActionPerformed);

        btnCancelarLibroActualizar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnCancelarLibroActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/X.png"))); // NOI18N
        btnCancelarLibroActualizar.setText("Cancelar");
        btnCancelarLibroActualizar.addActionListener(this::btnCancelarLibroActualizarActionPerformed);

        lblAutorLibroActualizar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblAutorLibroActualizar.setText("Autor");

        lblDisponibleLibroActualizar.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        lblDisponibleLibroActualizar.setText("Disponible");

        rbtnDisponibleLibroActualizar.addActionListener(this::rbtnDisponibleLibroActualizarActionPerformed);

        btnBuscarLibroActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarLibroActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/LUPA_.png"))); // NOI18N
        btnBuscarLibroActualizar.setText("Buscar");

        btnLimpiarLibroActualizar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnLimpiarLibroActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/Escoba.png"))); // NOI18N
        btnLimpiarLibroActualizar.setText("Limpiar");

        jLabel2.setFont(new java.awt.Font("Xolonium", 0, 24)); // NOI18N
        jLabel2.setText("Datos de el Libro");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/actualizarLibro.png"))); // NOI18N

        javax.swing.GroupLayout panelLibroActualizarLayout = new javax.swing.GroupLayout(panelLibroActualizar);
        panelLibroActualizar.setLayout(panelLibroActualizarLayout);
        panelLibroActualizarLayout.setHorizontalGroup(
            panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibroActualizarLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLibroActualizarLayout.createSequentialGroup()
                        .addComponent(lblIsbnLibroActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIsbnLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibroActualizarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLibroActualizarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(panelLibroActualizarLayout.createSequentialGroup()
                        .addComponent(lblYearLibroActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(txtYearLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(panelLibroActualizarLayout.createSequentialGroup()
                            .addComponent(lblAutorLibroActualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAutorLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelLibroActualizarLayout.createSequentialGroup()
                            .addComponent(lblEditorialLibroActualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEditorialLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLibroActualizarLayout.createSequentialGroup()
                            .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblGeneroLibroActualizar)
                                .addComponent(lblTituloLibroActualizar))
                            .addGap(97, 97, 97)
                            .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTituloLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGeneroLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(66, 66, 66))
            .addGroup(panelLibroActualizarLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLibroActualizarLayout.createSequentialGroup()
                        .addComponent(lblDisponibleLibroActualizar)
                        .addGap(53, 53, 53)
                        .addComponent(rbtnDisponibleLibroActualizar))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibroActualizarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizarLibroActualizar)
                .addGap(22, 22, 22)
                .addComponent(btnCancelarLibroActualizar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpiarLibroActualizar)
                .addGap(124, 124, 124))
        );
        panelLibroActualizarLayout.setVerticalGroup(
            panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibroActualizarLayout.createSequentialGroup()
                .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLibroActualizarLayout.createSequentialGroup()
                        .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTituloLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTituloLibroActualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtYearLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYearLibroActualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGeneroLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGeneroLibroActualizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEditorialLibroActualizar)
                            .addComponent(txtEditorialLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAutorLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutorLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbtnDisponibleLibroActualizar)
                            .addComponent(lblDisponibleLibroActualizar)))
                    .addGroup(panelLibroActualizarLayout.createSequentialGroup()
                        .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIsbnLibroActualizar)
                            .addComponent(txtIsbnLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(btnBuscarLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38)
                .addGroup(panelLibroActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarLibroActualizar)
                    .addComponent(btnCancelarLibroActualizar)
                    .addComponent(btnLimpiarLibroActualizar))
                .addGap(52, 52, 52))
        );

        getContentPane().add(panelLibroActualizar, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIsbnLibroActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnLibroActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsbnLibroActualizarActionPerformed

    private void txtTituloLibroActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloLibroActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloLibroActualizarActionPerformed

    private void btnActualizarLibroActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarLibroActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarLibroActualizarActionPerformed

    private void rbtnDisponibleLibroActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDisponibleLibroActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDisponibleLibroActualizarActionPerformed

    private void btnCancelarLibroActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarLibroActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarLibroActualizarActionPerformed

    private void txtYearLibroActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearLibroActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearLibroActualizarActionPerformed

    public void mostarMensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    public JButton getBtnActualizarLibroActualizar() {
        return btnActualizarLibroActualizar;
    }

    public JButton getBtnBuscarLibroActualizar() {
        return btnBuscarLibroActualizar;
    }

    public JButton getBtnCancelarLibroActualizar() {
        return btnCancelarLibroActualizar;
    }

    public JButton getBtnLimpiarLibroActualizar() {
        return btnLimpiarLibroActualizar;
    }

    public JRadioButton getRbtnDisponibleLibroActualizar() {
        return rbtnDisponibleLibroActualizar;
    }

    public JTextField getTxtAutorLibroActualizar() {
        return txtAutorLibroActualizar;
    }

    public JTextField getTxtEditorialLibroActualizar() {
        return txtEditorialLibroActualizar;
    }

    public JTextField getTxtGeneroLibroActualizar() {
        return txtGeneroLibroActualizar;
    }

    public JTextField getTxtIsbnLibroActualizar() {
        return txtIsbnLibroActualizar;
    }

    public JTextField getTxtTituloLibroActualizar() {
        return txtTituloLibroActualizar;
    }

    public JTextField getTxtYearLibroActualizar() {
        return txtYearLibroActualizar;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarLibroActualizar;
    private javax.swing.JButton btnBuscarLibroActualizar;
    private javax.swing.JButton btnCancelarLibroActualizar;
    private javax.swing.JButton btnLimpiarLibroActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAutorLibroActualizar;
    private javax.swing.JLabel lblDisponibleLibroActualizar;
    private javax.swing.JLabel lblEditorialLibroActualizar;
    private javax.swing.JLabel lblGeneroLibroActualizar;
    private javax.swing.JLabel lblIsbnLibroActualizar;
    private javax.swing.JLabel lblTituloLibroActualizar;
    private javax.swing.JLabel lblYearLibroActualizar;
    private javax.swing.JPanel panelLibroActualizar;
    private javax.swing.JRadioButton rbtnDisponibleLibroActualizar;
    private javax.swing.JTextField txtAutorLibroActualizar;
    private javax.swing.JTextField txtEditorialLibroActualizar;
    private javax.swing.JTextField txtGeneroLibroActualizar;
    private javax.swing.JTextField txtIsbnLibroActualizar;
    private javax.swing.JTextField txtTituloLibroActualizar;
    private javax.swing.JTextField txtYearLibroActualizar;
    // End of variables declaration//GEN-END:variables
}
