/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class LibroBuscarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form LibroBuscarView
     */
    public LibroBuscarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnLimpiarLibroCrear = new javax.swing.JButton();
        panelLibroBuscar = new javax.swing.JPanel();
        lblIsbnLibroBuscar = new javax.swing.JLabel();
        txtIsbnLibroBuscar = new javax.swing.JTextField();
        lblTituloLibroBuscar = new javax.swing.JLabel();
        lblYearLibroBuscar = new javax.swing.JLabel();
        lblGeneroLibroBuscar = new javax.swing.JLabel();
        lblEditorialLibroBuscar = new javax.swing.JLabel();
        txtTituloLibroBuscar = new javax.swing.JTextField();
        txtYearLibroBuscar = new javax.swing.JTextField();
        txtGeneroLibroBuscar = new javax.swing.JTextField();
        txtEditorialLibroBuscar = new javax.swing.JTextField();
        btnCrearLibroBuscar = new javax.swing.JButton();
        btnCancelarLibroBuscar = new javax.swing.JButton();
        lblAutorLibroBuscar = new javax.swing.JLabel();
        lblDisponibleLibroBuscar = new javax.swing.JLabel();
        txtAutorLibroBuscar = new javax.swing.JTextField();
        rbtnDisponibleLibroBuscar = new javax.swing.JRadioButton();
        btnLimpiarLibroBuscar = new javax.swing.JButton();

        btnLimpiarLibroCrear.setText("Limpiar");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblIsbnLibroBuscar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        lblIsbnLibroBuscar.setText("ISBN");
        lblIsbnLibroBuscar.setToolTipText("");

        txtIsbnLibroBuscar.addActionListener(this::txtIsbnLibroBuscarActionPerformed);

        lblTituloLibroBuscar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblTituloLibroBuscar.setText("Titulo");

        lblYearLibroBuscar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblYearLibroBuscar.setText("Año de publicación");

        lblGeneroLibroBuscar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblGeneroLibroBuscar.setText("Género");

        lblEditorialLibroBuscar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblEditorialLibroBuscar.setText("Editorial");

        txtTituloLibroBuscar.setEnabled(false);
        txtTituloLibroBuscar.addActionListener(this::txtTituloLibroBuscarActionPerformed);

        txtYearLibroBuscar.setEnabled(false);

        txtGeneroLibroBuscar.setEnabled(false);

        txtEditorialLibroBuscar.setEnabled(false);

        btnCrearLibroBuscar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCrearLibroBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/LUPA_.png"))); // NOI18N
        btnCrearLibroBuscar.setText("Buscar");
        btnCrearLibroBuscar.addActionListener(this::btnCrearLibroBuscarActionPerformed);

        btnCancelarLibroBuscar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCancelarLibroBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/X.png"))); // NOI18N
        btnCancelarLibroBuscar.setText("Cancelar");

        lblAutorLibroBuscar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblAutorLibroBuscar.setText("Autor");

        lblDisponibleLibroBuscar.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        lblDisponibleLibroBuscar.setText("Disponible");

        txtAutorLibroBuscar.setEnabled(false);

        rbtnDisponibleLibroBuscar.setEnabled(false);
        rbtnDisponibleLibroBuscar.addActionListener(this::rbtnDisponibleLibroBuscarActionPerformed);

        btnLimpiarLibroBuscar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLimpiarLibroBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/Escoba.png"))); // NOI18N
        btnLimpiarLibroBuscar.setText("Limpiar");
        btnLimpiarLibroBuscar.addActionListener(this::btnLimpiarLibroBuscarActionPerformed);

        javax.swing.GroupLayout panelLibroBuscarLayout = new javax.swing.GroupLayout(panelLibroBuscar);
        panelLibroBuscar.setLayout(panelLibroBuscarLayout);
        panelLibroBuscarLayout.setHorizontalGroup(
            panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                        .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDisponibleLibroBuscar)
                            .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblYearLibroBuscar)
                                    .addComponent(lblGeneroLibroBuscar))
                                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtGeneroLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtYearLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTituloLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rbtnDisponibleLibroBuscar)))
                                    .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(lblIsbnLibroBuscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                        .addComponent(txtIsbnLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(197, 197, 197))
                    .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                        .addComponent(lblTituloLibroBuscar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibroBuscarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelarLibroBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLimpiarLibroBuscar)
                            .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                                    .addComponent(lblAutorLibroBuscar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAutorLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                                    .addComponent(lblEditorialLibroBuscar)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtEditorialLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(65, 65, 65))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLibroBuscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCrearLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        panelLibroBuscarLayout.setVerticalGroup(
            panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIsbnLibroBuscar)
                    .addComponent(txtIsbnLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnCrearLibroBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloLibroBuscar)
                    .addComponent(txtTituloLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEditorialLibroBuscar)
                    .addComponent(txtEditorialLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblYearLibroBuscar)
                    .addComponent(txtYearLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLibroBuscarLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGeneroLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGeneroLibroBuscar)))
                    .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAutorLibroBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAutorLibroBuscar)))
                .addGap(36, 36, 36)
                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDisponibleLibroBuscar)
                    .addComponent(rbtnDisponibleLibroBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(panelLibroBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpiarLibroBuscar)
                    .addComponent(btnCancelarLibroBuscar))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLibroBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLibroBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIsbnLibroBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsbnLibroBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsbnLibroBuscarActionPerformed

    private void txtTituloLibroBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTituloLibroBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloLibroBuscarActionPerformed

    private void btnCrearLibroBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearLibroBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearLibroBuscarActionPerformed

    private void btnLimpiarLibroBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarLibroBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarLibroBuscarActionPerformed

    private void rbtnDisponibleLibroBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDisponibleLibroBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnDisponibleLibroBuscarActionPerformed

    public JButton getBtnCancelarLibroBuscar() {
        return btnCancelarLibroBuscar;
    }

    public void setBtnCancelarLibroBuscar(JButton btnCancelarLibroBuscar) {
        this.btnCancelarLibroBuscar = btnCancelarLibroBuscar;
    }

    public JButton getBtnCrearLibroBuscar() {
        return btnCrearLibroBuscar;
    }

    public void setBtnCrearLibroBuscar(JButton btnCrearLibroBuscar) {
        this.btnCrearLibroBuscar = btnCrearLibroBuscar;
    }

    public JButton getBtnLimpiarLibroBuscar() {
        return btnLimpiarLibroBuscar;
    }

    public void setBtnLimpiarLibroBuscar(JButton btnLimpiarLibroBuscar) {
        this.btnLimpiarLibroBuscar = btnLimpiarLibroBuscar;
    }

    public JRadioButton getRbtnDisponibleLibroBuscar() {
        return rbtnDisponibleLibroBuscar;
    }

    public void setRbtnDisponibleLibroBuscar(JRadioButton rbtnDisponibleLibroBuscar) {
        this.rbtnDisponibleLibroBuscar = rbtnDisponibleLibroBuscar;
    }

    public JTextField getTxtAutorLibroBuscar() {
        return txtAutorLibroBuscar;
    }

    public void setTxtAutorLibroBuscar(JTextField txtAutorLibroBuscar) {
        this.txtAutorLibroBuscar = txtAutorLibroBuscar;
    }

    public JTextField getTxtEditorialLibroBuscar() {
        return txtEditorialLibroBuscar;
    }

    public void setTxtEditorialLibroBuscar(JTextField txtEditorialLibroBuscar) {
        this.txtEditorialLibroBuscar = txtEditorialLibroBuscar;
    }

    public JTextField getTxtGeneroLibroBuscar() {
        return txtGeneroLibroBuscar;
    }

    public void setTxtGeneroLibroBuscar(JTextField txtGeneroLibroBuscar) {
        this.txtGeneroLibroBuscar = txtGeneroLibroBuscar;
    }

    public JTextField getTxtIsbnLibroBuscar() {
        return txtIsbnLibroBuscar;
    }

    public void setTxtIsbnLibroBuscar(JTextField txtIsbnLibroBuscar) {
        this.txtIsbnLibroBuscar = txtIsbnLibroBuscar;
    }

    public JTextField getTxtTituloLibroBuscar() {
        return txtTituloLibroBuscar;
    }

    public void setTxtTituloLibroBuscar(JTextField txtTituloLibroBuscar) {
        this.txtTituloLibroBuscar = txtTituloLibroBuscar;
    }

    public JTextField getTxtYearLibroBuscar() {
        return txtYearLibroBuscar;
    }

    public void setTxtYearLibroBuscar(JTextField txtYearLibroBuscar) {
        this.txtYearLibroBuscar = txtYearLibroBuscar;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarLibroBuscar;
    private javax.swing.JButton btnCrearLibroBuscar;
    private javax.swing.JButton btnLimpiarLibroBuscar;
    private javax.swing.JButton btnLimpiarLibroCrear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblAutorLibroBuscar;
    private javax.swing.JLabel lblDisponibleLibroBuscar;
    private javax.swing.JLabel lblEditorialLibroBuscar;
    private javax.swing.JLabel lblGeneroLibroBuscar;
    private javax.swing.JLabel lblIsbnLibroBuscar;
    private javax.swing.JLabel lblTituloLibroBuscar;
    private javax.swing.JLabel lblYearLibroBuscar;
    private javax.swing.JPanel panelLibroBuscar;
    private javax.swing.JRadioButton rbtnDisponibleLibroBuscar;
    private javax.swing.JTextField txtAutorLibroBuscar;
    private javax.swing.JTextField txtEditorialLibroBuscar;
    private javax.swing.JTextField txtGeneroLibroBuscar;
    private javax.swing.JTextField txtIsbnLibroBuscar;
    private javax.swing.JTextField txtTituloLibroBuscar;
    private javax.swing.JTextField txtYearLibroBuscar;
    // End of variables declaration//GEN-END:variables
}
