/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class PrestamoListarView extends javax.swing.JInternalFrame {
    
    private DefaultTableModel modelo;

    /**
     * Creates new form PrestamoLIstarView
     */
    public PrestamoListarView() {
        initComponents();
        configurarTabla();
    }
    
    private void configurarTabla() {

    modelo = new DefaultTableModel(new Object[]{"Código","Usuario","Cantidad de Libros","Fecha Préstamo","Estado"}, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    tblPrestamoPrestamoListar.setModel(modelo);

    tblPrestamoPrestamoListar.getTableHeader().setReorderingAllowed(false);

    tblPrestamoPrestamoListar.getTableHeader().setResizingAllowed(false);

}

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getTblPrestamoPrestamoListar() {
        return tblPrestamoPrestamoListar;
    }

    public void setTblPrestamoPrestamoListar(JTable tblPrestamoPrestamoListar) {
        this.tblPrestamoPrestamoListar = tblPrestamoPrestamoListar;
    }
    
    public void cambiarIdioma(Locale locale) {
        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);
        
        modelo.setColumnIdentifiers(new Object[]{
        bundle.getString("prestamo.codigo"),
        bundle.getString("usuario.nombre"),
        bundle.getString("prestamo.cantidadLibros"),
        bundle.getString("prestamo.fecha"),
        bundle.getString("prestamo.estado")
    });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamoPrestamoListar = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblPrestamoPrestamoListar.setBackground(new java.awt.Color(207, 162, 124));
        tblPrestamoPrestamoListar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblPrestamoPrestamoListar.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        tblPrestamoPrestamoListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPrestamoPrestamoListar.setEnabled(false);
        jScrollPane1.setViewportView(tblPrestamoPrestamoListar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 797, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrestamoPrestamoListar;
    // End of variables declaration//GEN-END:variables
}
