/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class PrestamoEliminarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PrestamoEliminarView
     */
    public PrestamoEliminarView() {
        initComponents();
        configurarTabla();
    }

    private void configurarTabla() {

        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{"ISBN", "Título"}, 0) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblLibrosPrestamoEliminar.setModel(modelo);

        tblLibrosPrestamoEliminar.getTableHeader().setReorderingAllowed(false);

        tblLibrosPrestamoEliminar.getTableHeader().setResizingAllowed(false);

    }
    
    public void cambiarIdioma(Locale locale) {
        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);
        
        lblCodigoPrestamoEliminar.setText(bundle.getString("prestamo.codigo"));
    lblCedulaPrestamoEliminar.setText(bundle.getString("usuario.cedula"));
    lblNombrePrestamoEliminar.setText(bundle.getString("usuario.nombre"));
    lblTelefonoPrestamoEliminar.setText(bundle.getString("usuario.telefono"));
    lblFechaPrestamoEliminar.setText(bundle.getString("prestamo.fecha"));
    lblTituloTblPrestamoEliminar.setText(bundle.getString("prestamo.libros"));

    btnBuscarPrestamoEliminar.setText(bundle.getString("boton.buscar"));
    btnEliminarPrestamoEliminar.setText(bundle.getString("boton.eliminar"));
    btnLimpiarPrestamoEliminar.setText(bundle.getString("boton.limpiar"));
    btnCancelarPrestamoEliminar.setText(bundle.getString("boton.cancelar"));

    DefaultTableModel modelo = (DefaultTableModel) tblLibrosPrestamoEliminar.getModel();

    modelo.setColumnIdentifiers(new Object[]{
        bundle.getString("libro.isbn"),
        bundle.getString("libro.titulo")
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCedulaPrestamoEliminar = new javax.swing.JLabel();
        txtCedulaPrestamoEliminar = new javax.swing.JTextField();
        lblNombrePrestamoEliminar = new javax.swing.JLabel();
        txtNombrePrestamoEliminar = new javax.swing.JTextField();
        lblTelefonoPrestamoEliminar = new javax.swing.JLabel();
        txtTelefonoPrestamoEliminar = new javax.swing.JTextField();
        lblFechaPrestamoEliminar = new javax.swing.JLabel();
        lblCodigoPrestamoEliminar = new javax.swing.JLabel();
        txtFechaPrestamoEliminar = new javax.swing.JTextField();
        txtCodigoPrestamoEliminar = new javax.swing.JTextField();
        lblTituloTblPrestamoEliminar = new javax.swing.JLabel();
        btnBuscarPrestamoEliminar = new javax.swing.JButton();
        btnLimpiarPrestamoEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibrosPrestamoEliminar = new javax.swing.JTable();
        btnEliminarPrestamoEliminar = new javax.swing.JButton();
        btnCancelarPrestamoEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(207, 162, 124));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(768, 880));

        lblCedulaPrestamoEliminar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblCedulaPrestamoEliminar.setText("Cédula:");

        txtCedulaPrestamoEliminar.setEnabled(false);

        lblNombrePrestamoEliminar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblNombrePrestamoEliminar.setText("Nombre:");

        txtNombrePrestamoEliminar.setEnabled(false);

        lblTelefonoPrestamoEliminar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblTelefonoPrestamoEliminar.setText("Teléfono:");

        txtTelefonoPrestamoEliminar.setEnabled(false);

        lblFechaPrestamoEliminar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblFechaPrestamoEliminar.setText("Fecha del préstamo:");

        lblCodigoPrestamoEliminar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblCodigoPrestamoEliminar.setText("Código del préstamo:");

        txtFechaPrestamoEliminar.setEnabled(false);

        lblTituloTblPrestamoEliminar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblTituloTblPrestamoEliminar.setText("Libro/s prestado/s");

        btnBuscarPrestamoEliminar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnBuscarPrestamoEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/LUPA_.png"))); // NOI18N
        btnBuscarPrestamoEliminar.setText("Buscar");

        btnLimpiarPrestamoEliminar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLimpiarPrestamoEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/Escoba.png"))); // NOI18N
        btnLimpiarPrestamoEliminar.setText("Limpiar");

        tblLibrosPrestamoEliminar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLibrosPrestamoEliminar);

        btnEliminarPrestamoEliminar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEliminarPrestamoEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/eliminar.png"))); // NOI18N
        btnEliminarPrestamoEliminar.setText("Eliminar");
        btnEliminarPrestamoEliminar.addActionListener(this::btnEliminarPrestamoEliminarActionPerformed);

        btnCancelarPrestamoEliminar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCancelarPrestamoEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/X.png"))); // NOI18N
        btnCancelarPrestamoEliminar.setText("Cancelar");

        jLabel1.setBackground(new java.awt.Color(207, 162, 124));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/Eprestamo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCedulaPrestamoEliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNombrePrestamoEliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTelefonoPrestamoEliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFechaPrestamoEliminar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaPrestamoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtCedulaPrestamoEliminar, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTelefonoPrestamoEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNombrePrestamoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoPrestamoEliminar)
                            .addComponent(txtCodigoPrestamoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBuscarPrestamoEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimpiarPrestamoEliminar)))
                        .addGap(8, 8, 8)))
                .addGap(0, 118, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(lblTituloTblPrestamoEliminar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(btnEliminarPrestamoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarPrestamoEliminar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCodigoPrestamoEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigoPrestamoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscarPrestamoEliminar)
                            .addComponent(btnLimpiarPrestamoEliminar)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePrestamoEliminar)
                    .addComponent(txtNombrePrestamoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCedulaPrestamoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedulaPrestamoEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoPrestamoEliminar)
                    .addComponent(txtTelefonoPrestamoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaPrestamoEliminar)
                    .addComponent(txtFechaPrestamoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloTblPrestamoEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarPrestamoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarPrestamoEliminar))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarPrestamoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPrestamoEliminarActionPerformed

       
    }//GEN-LAST:event_btnEliminarPrestamoEliminarActionPerformed

    public JButton getBtnBuscarPrestamoEliminar() {
        return btnBuscarPrestamoEliminar;
    }

    public void setBtnBuscarPrestamoEliminar(JButton btnBuscarPrestamoEliminar) {
        this.btnBuscarPrestamoEliminar = btnBuscarPrestamoEliminar;
    }

    public JButton getBtnCancelarPrestamoEliminar() {
        return btnCancelarPrestamoEliminar;
    }

    public void setBtnCancelarPrestamoEliminar(JButton btnCancelarPrestamoEliminar) {
        this.btnCancelarPrestamoEliminar = btnCancelarPrestamoEliminar;
    }

    public JButton getBtnEliminarPrestamoEliminar() {
        return btnEliminarPrestamoEliminar;
    }

    public void setBtnEliminarPrestamoEliminar(JButton btnEliminarPrestamoEliminar) {
        this.btnEliminarPrestamoEliminar = btnEliminarPrestamoEliminar;
    }

    public JButton getBtnLimpiarPrestamoEliminar() {
        return btnLimpiarPrestamoEliminar;
    }

    public void setBtnLimpiarPrestamoEliminar(JButton btnLimpiarPrestamoEliminar) {
        this.btnLimpiarPrestamoEliminar = btnLimpiarPrestamoEliminar;
    }

    public JTable getTblLibrosPrestamoEliminar() {
        return tblLibrosPrestamoEliminar;
    }

    public void setTblLibrosPrestamoEliminar(JTable tblLibrosPrestamoEliminar) {
        this.tblLibrosPrestamoEliminar = tblLibrosPrestamoEliminar;
    }

    public JTextField getTxtCedulaPrestamoEliminar() {
        return txtCedulaPrestamoEliminar;
    }

    public void setTxtCedulaPrestamoEliminar(JTextField txtCedulaPrestamoEliminar) {
        this.txtCedulaPrestamoEliminar = txtCedulaPrestamoEliminar;
    }

    public JTextField getTxtCodigoPrestamoEliminar() {
        return txtCodigoPrestamoEliminar;
    }

    public void setTxtCodigoPrestamoEliminar(JTextField txtCodigoPrestamoEliminar) {
        this.txtCodigoPrestamoEliminar = txtCodigoPrestamoEliminar;
    }

    public JTextField getTxtFechaPrestamoEliminar() {
        return txtFechaPrestamoEliminar;
    }

    public void setTxtFechaPrestamoEliminar(JTextField txtFechaPrestamoEliminar) {
        this.txtFechaPrestamoEliminar = txtFechaPrestamoEliminar;
    }

    public JTextField getTxtNombrePrestamoEliminar() {
        return txtNombrePrestamoEliminar;
    }

    public void setTxtNombrePrestamoEliminar(JTextField txtNombrePrestamoEliminar) {
        this.txtNombrePrestamoEliminar = txtNombrePrestamoEliminar;
    }

    public JTextField getTxtTelefonoPrestamoEliminar() {
        return txtTelefonoPrestamoEliminar;
    }

    public void setTxtTelefonoPrestamoEliminar(JTextField txtTelefonoPrestamoEliminar) {
        this.txtTelefonoPrestamoEliminar = txtTelefonoPrestamoEliminar;
    }

    public void mostarMensaje(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }
    
    public boolean confirmarEliminacion() {
    int opcion = javax.swing.JOptionPane.showConfirmDialog(this,"¿Está seguro de eliminar este préstamo?","Confirmar eliminación",javax.swing.JOptionPane.YES_NO_OPTION);
    return opcion == javax.swing.JOptionPane.YES_OPTION;
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarPrestamoEliminar;
    private javax.swing.JButton btnCancelarPrestamoEliminar;
    private javax.swing.JButton btnEliminarPrestamoEliminar;
    private javax.swing.JButton btnLimpiarPrestamoEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedulaPrestamoEliminar;
    private javax.swing.JLabel lblCodigoPrestamoEliminar;
    private javax.swing.JLabel lblFechaPrestamoEliminar;
    private javax.swing.JLabel lblNombrePrestamoEliminar;
    private javax.swing.JLabel lblTelefonoPrestamoEliminar;
    private javax.swing.JLabel lblTituloTblPrestamoEliminar;
    private javax.swing.JTable tblLibrosPrestamoEliminar;
    private javax.swing.JTextField txtCedulaPrestamoEliminar;
    private javax.swing.JTextField txtCodigoPrestamoEliminar;
    private javax.swing.JTextField txtFechaPrestamoEliminar;
    private javax.swing.JTextField txtNombrePrestamoEliminar;
    private javax.swing.JTextField txtTelefonoPrestamoEliminar;
    // End of variables declaration//GEN-END:variables
}
