/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class PrestamoBuscarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PrestamoBuscarView
     */
    public PrestamoBuscarView() {
        initComponents();
        configurarTabla();
    }
    
    public void cambiarIdioma(Locale locale) {
        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);

        lblCodigoPrestamoBuscar.setText(bundle.getString("prestamo.codigo"));
        lblOPrestamoBuscar.setText(bundle.getString("prestamo.o"));
        lblTemaTablaPrestamoBuscar.setText(bundle.getString("prestamo.resultados"));

        btnBuscarCodigoPrestamoBuscar.setText(bundle.getString("boton.buscar"));
        btnBuscarCedulaPrestamoBuscar.setText(bundle.getString("boton.buscar"));
        btnCancelarPrestamoBuscar.setText(bundle.getString("boton.cancelar"));

        DefaultTableModel modelo = (DefaultTableModel) tblPrestamosPrestamosBuscar.getModel();

        modelo.setColumnIdentifiers(new Object[]{
            bundle.getString("prestamo.codigo"),
            bundle.getString("usuario.cedula"),
            bundle.getString("usuario.nombre"),
            bundle.getString("prestamo.fecha"),
            bundle.getString("prestamo.devolucion")
        });
    }

    private void configurarTabla() {

        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Código", "Usuario", "Título del Libro", "Fecha Préstamo", "Estado"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblPrestamosPrestamosBuscar.setModel(modelo);

        tblPrestamosPrestamosBuscar.getTableHeader().setReorderingAllowed(false);

        tblPrestamosPrestamosBuscar.getTableHeader().setResizingAllowed(false);

    }

    public JButton getBtnBuscarCedulaPrestamoBuscar() {
        return btnBuscarCedulaPrestamoBuscar;
    }

    public void setBtnBuscarCedulaPrestamoBuscar(JButton btnBuscarCedulaPrestamoBuscar) {
        this.btnBuscarCedulaPrestamoBuscar = btnBuscarCedulaPrestamoBuscar;
    }

    public JButton getBtnBuscarCodigoPrestamoBuscar() {
        return btnBuscarCodigoPrestamoBuscar;
    }

    public void setBtnBuscarCodigoPrestamoBuscar(JButton btnBuscarCodigoPrestamoBuscar) {
        this.btnBuscarCodigoPrestamoBuscar = btnBuscarCodigoPrestamoBuscar;
    }

    public JButton getBtnCancelarPrestamoBuscar() {
        return btnCancelarPrestamoBuscar;
    }

    public void setBtnCancelarPrestamoBuscar(JButton btnCancelarPrestamoBuscar) {
        this.btnCancelarPrestamoBuscar = btnCancelarPrestamoBuscar;
    }

    public JTable getTblPrestamosPrestamosBuscar() {
        return tblPrestamosPrestamosBuscar;
    }

    public void setTblPrestamosPrestamosBuscar(JTable tblPrestamosPrestamosBuscar) {
        this.tblPrestamosPrestamosBuscar = tblPrestamosPrestamosBuscar;
    }

    public JTextField getTxtCedulaPrestamoBuscar() {
        return txtCedulaPrestamoBuscar;
    }

    public JComboBox<String> getCbxCedulaPrestamoBuscar() {
        return cbxCedulaPrestamoBuscar;
    }

    public void setTxtCedulaPrestamoBuscar(JTextField txtCedulaPrestamoBuscar) {
        this.txtCedulaPrestamoBuscar = txtCedulaPrestamoBuscar;
    }

    public JTextField getTxtCodigoPrestamoBuscar() {
        return txtCodigoPrestamoBuscar;
    }

    public JComboBox<String> getCbxCodigoPrestamoBuscar() {
        return cbxCodigoPrestamoBuscar;
    }

    public void setTxtCodigoPrestamoBuscar(JTextField txtCodigoPrestamoBuscar) {
        this.txtCodigoPrestamoBuscar = txtCodigoPrestamoBuscar;
    }

    public void mostarMensaje(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblCodigoPrestamoBuscar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoPrestamoBuscar = new javax.swing.JTextField();
        lblOPrestamoBuscar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCedulaPrestamoBuscar = new javax.swing.JTextField();
        btnBuscarCedulaPrestamoBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamosPrestamosBuscar = new javax.swing.JTable();
        lblTemaTablaPrestamoBuscar = new javax.swing.JLabel();
        btnCancelarPrestamoBuscar = new javax.swing.JButton();
        btnBuscarCodigoPrestamoBuscar = new javax.swing.JButton();
        cbxCedulaPrestamoBuscar = new javax.swing.JComboBox<>();
        cbxCodigoPrestamoBuscar = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(207, 162, 124));
        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel3.setBackground(new java.awt.Color(207, 162, 124));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblCodigoPrestamoBuscar.setFont(new java.awt.Font("Yu Gothic", 3, 14)); // NOI18N
        lblCodigoPrestamoBuscar.setText("Código:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/Bprestamo-Photoroom.png"))); // NOI18N

        lblOPrestamoBuscar.setText("O");

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 3, 14)); // NOI18N
        jLabel2.setText("Cédula del usuario:");

        btnBuscarCedulaPrestamoBuscar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnBuscarCedulaPrestamoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/LUPA_.png"))); // NOI18N
        btnBuscarCedulaPrestamoBuscar.setText("Buscar");

        tblPrestamosPrestamosBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPrestamosPrestamosBuscar);

        lblTemaTablaPrestamoBuscar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTemaTablaPrestamoBuscar.setText("Prestamos encontrados");

        btnCancelarPrestamoBuscar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnCancelarPrestamoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/X-.png"))); // NOI18N
        btnCancelarPrestamoBuscar.setText("Cancelar");

        btnBuscarCodigoPrestamoBuscar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnBuscarCodigoPrestamoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/LUPA_.png"))); // NOI18N
        btnBuscarCodigoPrestamoBuscar.setText("Buscar");

        cbxCedulaPrestamoBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxCodigoPrestamoBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(lblTemaTablaPrestamoBuscar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnCancelarPrestamoBuscar)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblOPrestamoBuscar)
                        .addComponent(jLabel2))
                    .addComponent(lblCodigoPrestamoBuscar))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodigoPrestamoBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtCedulaPrestamoBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbxCedulaPrestamoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarCedulaPrestamoBuscar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbxCodigoPrestamoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarCodigoPrestamoBuscar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtCedulaPrestamoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxCedulaPrestamoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addComponent(lblOPrestamoBuscar)
                                .addGap(12, 12, 12))
                            .addComponent(btnBuscarCedulaPrestamoBuscar, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCodigoPrestamoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBuscarCodigoPrestamoBuscar)
                                .addComponent(cbxCodigoPrestamoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCodigoPrestamoBuscar))
                        .addGap(36, 36, 36)))
                .addComponent(lblTemaTablaPrestamoBuscar)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(btnCancelarPrestamoBuscar)))
                .addGap(142, 142, 142))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCedulaPrestamoBuscar;
    private javax.swing.JButton btnBuscarCodigoPrestamoBuscar;
    private javax.swing.JButton btnCancelarPrestamoBuscar;
    private javax.swing.JComboBox<String> cbxCedulaPrestamoBuscar;
    private javax.swing.JComboBox<String> cbxCodigoPrestamoBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigoPrestamoBuscar;
    private javax.swing.JLabel lblOPrestamoBuscar;
    private javax.swing.JLabel lblTemaTablaPrestamoBuscar;
    private javax.swing.JTable tblPrestamosPrestamosBuscar;
    private javax.swing.JTextField txtCedulaPrestamoBuscar;
    private javax.swing.JTextField txtCodigoPrestamoBuscar;
    // End of variables declaration//GEN-END:variables
}
