/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

/**
 *
 * @author USER
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuItemLibro = new javax.swing.JMenu();
        menuItemLibroCrear = new javax.swing.JMenuItem();
        menuItemLibroBuscar = new javax.swing.JMenuItem();
        menuItemLibroActualizar = new javax.swing.JMenuItem();
        menuItemLibroEliminar = new javax.swing.JMenuItem();
        menuItemLibroListar = new javax.swing.JMenuItem();
        menuItemUsuario = new javax.swing.JMenu();
        menuItemUsuarioCrear = new javax.swing.JMenuItem();
        menuItemUsuarioBuscar = new javax.swing.JMenuItem();
        menuItemUsuarioActualizar = new javax.swing.JMenuItem();
        menuItemUsuarioEliminar = new javax.swing.JMenuItem();
        menuItemUsuarioListar = new javax.swing.JMenuItem();
        menuItemPrestamo = new javax.swing.JMenu();
        menuItemPrestamoCrear = new javax.swing.JMenuItem();
        menuItemPrestamoBuscar = new javax.swing.JMenuItem();
        menuItemPrestamoActualizar = new javax.swing.JMenuItem();
        menuItemPrestamoEliminar = new javax.swing.JMenuItem();
        menuItemPrestamoListar = new javax.swing.JMenuItem();
        menuItemIdioma = new javax.swing.JMenu();
        menuItemIdiomaEspañol = new javax.swing.JMenuItem();
        menuItemIdiomaIngles = new javax.swing.JMenuItem();
        menuItemSistema = new javax.swing.JMenu();
        menuItemSistemaSalir = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuItemLibro.setMnemonic('f');
        menuItemLibro.setText("Libro");

        menuItemLibroCrear.setMnemonic('o');
        menuItemLibroCrear.setText("Crear");
        menuItemLibro.add(menuItemLibroCrear);

        menuItemLibroBuscar.setMnemonic('s');
        menuItemLibroBuscar.setText("Buscar");
        menuItemLibro.add(menuItemLibroBuscar);

        menuItemLibroActualizar.setMnemonic('a');
        menuItemLibroActualizar.setText("Actualizar");
        menuItemLibro.add(menuItemLibroActualizar);

        menuItemLibroEliminar.setMnemonic('x');
        menuItemLibroEliminar.setText("Eliminar");
        menuItemLibroEliminar.addActionListener(this::menuItemLibroEliminarActionPerformed);
        menuItemLibro.add(menuItemLibroEliminar);

        menuItemLibroListar.setText("Lista");
        menuItemLibro.add(menuItemLibroListar);

        menuBar.add(menuItemLibro);

        menuItemUsuario.setMnemonic('e');
        menuItemUsuario.setText("Usuario");

        menuItemUsuarioCrear.setMnemonic('t');
        menuItemUsuarioCrear.setText("Crear");
        menuItemUsuario.add(menuItemUsuarioCrear);

        menuItemUsuarioBuscar.setMnemonic('y');
        menuItemUsuarioBuscar.setText("Buscar");
        menuItemUsuario.add(menuItemUsuarioBuscar);

        menuItemUsuarioActualizar.setMnemonic('p');
        menuItemUsuarioActualizar.setText("Actualizar");
        menuItemUsuario.add(menuItemUsuarioActualizar);

        menuItemUsuarioEliminar.setMnemonic('d');
        menuItemUsuarioEliminar.setText("Eliminar");
        menuItemUsuario.add(menuItemUsuarioEliminar);

        menuItemUsuarioListar.setText("Lista");
        menuItemUsuario.add(menuItemUsuarioListar);

        menuBar.add(menuItemUsuario);

        menuItemPrestamo.setMnemonic('h');
        menuItemPrestamo.setText("Prestamo");

        menuItemPrestamoCrear.setMnemonic('c');
        menuItemPrestamoCrear.setText("Crear");
        menuItemPrestamo.add(menuItemPrestamoCrear);

        menuItemPrestamoBuscar.setMnemonic('a');
        menuItemPrestamoBuscar.setText("Buscar");
        menuItemPrestamo.add(menuItemPrestamoBuscar);

        menuItemPrestamoActualizar.setText("Actualizar");
        menuItemPrestamo.add(menuItemPrestamoActualizar);

        menuItemPrestamoEliminar.setText("Eliminar");
        menuItemPrestamo.add(menuItemPrestamoEliminar);

        menuItemPrestamoListar.setText("Lista");
        menuItemPrestamo.add(menuItemPrestamoListar);

        menuBar.add(menuItemPrestamo);

        menuItemIdioma.setText("Idioma");

        menuItemIdiomaEspañol.setText("Español");
        menuItemIdioma.add(menuItemIdiomaEspañol);

        menuItemIdiomaIngles.setText("Ingles");
        menuItemIdioma.add(menuItemIdiomaIngles);

        menuBar.add(menuItemIdioma);

        menuItemSistema.setText("Sistema");

        menuItemSistemaSalir.setText("Salir");
        menuItemSistema.add(menuItemSistemaSalir);

        menuBar.add(menuItemSistema);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemLibroEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLibroEliminarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemLibroEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuItemIdioma;
    private javax.swing.JMenuItem menuItemIdiomaEspañol;
    private javax.swing.JMenuItem menuItemIdiomaIngles;
    private javax.swing.JMenu menuItemLibro;
    private javax.swing.JMenuItem menuItemLibroActualizar;
    private javax.swing.JMenuItem menuItemLibroBuscar;
    private javax.swing.JMenuItem menuItemLibroCrear;
    private javax.swing.JMenuItem menuItemLibroEliminar;
    private javax.swing.JMenuItem menuItemLibroListar;
    private javax.swing.JMenu menuItemPrestamo;
    private javax.swing.JMenuItem menuItemPrestamoActualizar;
    private javax.swing.JMenuItem menuItemPrestamoBuscar;
    private javax.swing.JMenuItem menuItemPrestamoCrear;
    private javax.swing.JMenuItem menuItemPrestamoEliminar;
    private javax.swing.JMenuItem menuItemPrestamoListar;
    private javax.swing.JMenu menuItemSistema;
    private javax.swing.JMenuItem menuItemSistemaSalir;
    private javax.swing.JMenu menuItemUsuario;
    private javax.swing.JMenuItem menuItemUsuarioActualizar;
    private javax.swing.JMenuItem menuItemUsuarioBuscar;
    private javax.swing.JMenuItem menuItemUsuarioCrear;
    private javax.swing.JMenuItem menuItemUsuarioEliminar;
    private javax.swing.JMenuItem menuItemUsuarioListar;
    // End of variables declaration//GEN-END:variables

}
