/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class RegistrarDevolucionView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PrestamoActualizarView
     */
    public RegistrarDevolucionView() {
        initComponents();
        configurarTabla();
    }

    private void configurarTabla() {

        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{"ISBN", "Título"}, 0) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblLibrosRegistrarDevolucion.setModel(modelo);

        tblLibrosRegistrarDevolucion.getTableHeader().setReorderingAllowed(false);

        tblLibrosRegistrarDevolucion.getTableHeader().setResizingAllowed(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistrarDevolución = new javax.swing.JPanel();
        lblCodigoRegistrarDevolucion = new javax.swing.JLabel();
        txtCodigoRegistarDevolucion = new javax.swing.JTextField();
        btnBuscarRegistrarDevolucion = new javax.swing.JButton();
        lblFechaPrestamoRegistrarDevolucion = new javax.swing.JLabel();
        txtFechaPrestamoRegistrarDevolucion = new javax.swing.JTextField();
        lblFechaDevolucionRegistrarDevolucion = new javax.swing.JLabel();
        txtFechaDevolucionRegistrarDevolucion = new javax.swing.JTextField();
        btnLimpiarRegistrarDevolucion = new javax.swing.JButton();
        lblEstadoRegistrarDevolucion = new javax.swing.JLabel();
        txtEstadoRegistrarDevolucion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibrosRegistrarDevolucion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnDevolverRegistrarDevolucion = new javax.swing.JButton();
        btnCancelarRegistrarDevolucion = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        lblCodigoRegistrarDevolucion.setText("Código del prestamo:");

        btnBuscarRegistrarDevolucion.setText("Buscar");

        lblFechaPrestamoRegistrarDevolucion.setText("Fecha del prestamo:");

        txtFechaPrestamoRegistrarDevolucion.setEnabled(false);

        lblFechaDevolucionRegistrarDevolucion.setText("Fecha de devolucion:");

        txtFechaDevolucionRegistrarDevolucion.setEnabled(false);

        btnLimpiarRegistrarDevolucion.setText("Limpiar");

        lblEstadoRegistrarDevolucion.setText("Estado:");

        txtEstadoRegistrarDevolucion.setEnabled(false);

        tblLibrosRegistrarDevolucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLibrosRegistrarDevolucion);

        jLabel1.setText("Libro/s prestado/s");

        btnDevolverRegistrarDevolucion.setText("Devolver");

        btnCancelarRegistrarDevolucion.setText("Cancelar");

        javax.swing.GroupLayout panelRegistrarDevoluciónLayout = new javax.swing.GroupLayout(panelRegistrarDevolución);
        panelRegistrarDevolución.setLayout(panelRegistrarDevoluciónLayout);
        panelRegistrarDevoluciónLayout.setHorizontalGroup(
            panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarDevoluciónLayout.createSequentialGroup()
                .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarDevoluciónLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRegistrarDevoluciónLayout.createSequentialGroup()
                                .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblEstadoRegistrarDevolucion)
                                    .addComponent(lblFechaDevolucionRegistrarDevolucion)
                                    .addComponent(lblFechaPrestamoRegistrarDevolucion)
                                    .addComponent(lblCodigoRegistrarDevolucion))
                                .addGap(18, 18, 18)
                                .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtFechaPrestamoRegistrarDevolucion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                        .addComponent(txtEstadoRegistrarDevolucion, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFechaDevolucionRegistrarDevolucion, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(panelRegistrarDevoluciónLayout.createSequentialGroup()
                                        .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(txtCodigoRegistarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscarRegistrarDevolucion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnLimpiarRegistrarDevolucion))))))
                    .addGroup(panelRegistrarDevoluciónLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(btnDevolverRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(btnCancelarRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        panelRegistrarDevoluciónLayout.setVerticalGroup(
            panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarDevoluciónLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoRegistrarDevolucion)
                    .addComponent(txtCodigoRegistarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRegistrarDevolucion)
                    .addComponent(btnLimpiarRegistrarDevolucion))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaPrestamoRegistrarDevolucion)
                    .addComponent(txtFechaPrestamoRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaDevolucionRegistrarDevolucion)
                    .addComponent(txtFechaDevolucionRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoRegistrarDevolucion)
                    .addComponent(txtEstadoRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDevolverRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarRegistrarDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRegistrarDevolución, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRegistrarDevolución, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnBuscarRegistrarDevolucion() {
        return btnBuscarRegistrarDevolucion;
    }

    public void setBtnBuscarRegistrarDevolucion(JButton btnBuscarRegistrarDevolucion) {
        this.btnBuscarRegistrarDevolucion = btnBuscarRegistrarDevolucion;
    }

    public JButton getBtnCancelarRegistrarDevolucion() {
        return btnCancelarRegistrarDevolucion;
    }

    public void setBtnCancelarRegistrarDevolucion(JButton btnCancelarRegistrarDevolucion) {
        this.btnCancelarRegistrarDevolucion = btnCancelarRegistrarDevolucion;
    }

    public JButton getBtnDevolverRegistrarDevolucion() {
        return btnDevolverRegistrarDevolucion;
    }

    public void setBtnDevolverRegistrarDevolucion(JButton btnDevolverRegistrarDevolucion) {
        this.btnDevolverRegistrarDevolucion = btnDevolverRegistrarDevolucion;
    }

    public JButton getBtnLimpiarRegistrarDevolucion() {
        return btnLimpiarRegistrarDevolucion;
    }

    public void setBtnLimpiarRegistrarDevolucion(JButton btnLimpiarRegistrarDevolucion) {
        this.btnLimpiarRegistrarDevolucion = btnLimpiarRegistrarDevolucion;
    }

    public JPanel getPanelRegistrarDevolución() {
        return panelRegistrarDevolución;
    }

    public void setPanelRegistrarDevolución(JPanel panelRegistrarDevolución) {
        this.panelRegistrarDevolución = panelRegistrarDevolución;
    }

    public JTable getTblLibrosRegistrarDevolucion() {
        return tblLibrosRegistrarDevolucion;
    }

    public void setTblLibrosRegistrarDevolucion(JTable tblLibrosRegistrarDevolucion) {
        this.tblLibrosRegistrarDevolucion = tblLibrosRegistrarDevolucion;
    }

    public JTextField getTxtCodigoRegistarDevolucion() {
        return txtCodigoRegistarDevolucion;
    }

    public void setTxtCodigoRegistarDevolucion(JTextField txtCodigoRegistarDevolucion) {
        this.txtCodigoRegistarDevolucion = txtCodigoRegistarDevolucion;
    }

    public JTextField getTxtEstadoRegistrarDevolucion() {
        return txtEstadoRegistrarDevolucion;
    }

    public void setTxtEstadoRegistrarDevolucion(JTextField txtEstadoRegistrarDevolucion) {
        this.txtEstadoRegistrarDevolucion = txtEstadoRegistrarDevolucion;
    }

    public JTextField getTxtFechaDevolucionRegistrarDevolucion() {
        return txtFechaDevolucionRegistrarDevolucion;
    }

    public void setTxtFechaDevolucionRegistrarDevolucion(JTextField txtFechaDevolucionRegistrarDevolucion) {
        this.txtFechaDevolucionRegistrarDevolucion = txtFechaDevolucionRegistrarDevolucion;
    }

    public JTextField getTxtFechaPrestamoRegistrarDevolucion() {
        return txtFechaPrestamoRegistrarDevolucion;
    }

    public void setTxtFechaPrestamoRegistrarDevolucion(JTextField txtFechaPrestamoRegistrarDevolucion) {
        this.txtFechaPrestamoRegistrarDevolucion = txtFechaPrestamoRegistrarDevolucion;
    }

    public void mostarMensaje(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarRegistrarDevolucion;
    private javax.swing.JButton btnCancelarRegistrarDevolucion;
    private javax.swing.JButton btnDevolverRegistrarDevolucion;
    private javax.swing.JButton btnLimpiarRegistrarDevolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigoRegistrarDevolucion;
    private javax.swing.JLabel lblEstadoRegistrarDevolucion;
    private javax.swing.JLabel lblFechaDevolucionRegistrarDevolucion;
    private javax.swing.JLabel lblFechaPrestamoRegistrarDevolucion;
    private javax.swing.JPanel panelRegistrarDevolución;
    private javax.swing.JTable tblLibrosRegistrarDevolucion;
    private javax.swing.JTextField txtCodigoRegistarDevolucion;
    private javax.swing.JTextField txtEstadoRegistrarDevolucion;
    private javax.swing.JTextField txtFechaDevolucionRegistrarDevolucion;
    private javax.swing.JTextField txtFechaPrestamoRegistrarDevolucion;
    // End of variables declaration//GEN-END:variables
}
