/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class RegistrarDevolucionView extends javax.swing.JInternalFrame {

    /**
     * Creates new form PrestamoActualizarView
     */
    public RegistrarDevolucionView() {
        initComponents();
        configurarTabla();
    }

    private void configurarTabla() {

        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{"ISBN", "Título"}, 0) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblLibrosRegistrarDevolucion.setModel(modelo);

        tblLibrosRegistrarDevolucion.getTableHeader().setReorderingAllowed(false);

        tblLibrosRegistrarDevolucion.getTableHeader().setResizingAllowed(false);

    }
    
    public void cambiarIdioma(Locale locale) {
        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);
        
        lblCodigoRegistrarDevolucion.setText(bundle.getString("prestamo.codigo"));
    lblFechaPrestamoRegistrarDevolucion.setText(bundle.getString("prestamo.fecha"));
    lblFechaDevolucionRegistrarDevolucion.setText(bundle.getString("prestamo.fechaDevolucion"));
    lblEstadoRegistrarDevolucion.setText(bundle.getString("prestamo.estado"));

    btnBuscarRegistrarDevolucion.setText(bundle.getString("boton.buscar"));
    btnDevolverRegistrarDevolucion.setText(bundle.getString("boton.devolver"));
    btnLimpiarRegistrarDevolucion.setText(bundle.getString("boton.limpiar"));
    btnCancelarRegistrarDevolucion.setText(bundle.getString("boton.cancelar"));

    jLabel1.setText(bundle.getString("prestamo.devolucion.titulo"));
    jLabel2.setText(bundle.getString("prestamo.libros"));

    DefaultTableModel modelo = (DefaultTableModel) tblLibrosRegistrarDevolucion.getModel();

    modelo.setColumnIdentifiers(new Object[]{
        bundle.getString("libro.isbn"),
        bundle.getString("libro.titulo")
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRegistrarDevolución = new javax.swing.JPanel();
        lblCodigoRegistrarDevolucion = new javax.swing.JLabel();
        txtCodigoRegistarDevolucion = new javax.swing.JTextField();
        btnBuscarRegistrarDevolucion = new javax.swing.JButton();
        lblFechaPrestamoRegistrarDevolucion = new javax.swing.JLabel();
        txtFechaPrestamoRegistrarDevolucion = new javax.swing.JTextField();
        lblFechaDevolucionRegistrarDevolucion = new javax.swing.JLabel();
        txtFechaDevolucionRegistrarDevolucion = new javax.swing.JTextField();
        btnLimpiarRegistrarDevolucion = new javax.swing.JButton();
        lblEstadoRegistrarDevolucion = new javax.swing.JLabel();
        txtEstadoRegistrarDevolucion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibrosRegistrarDevolucion = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnDevolverRegistrarDevolucion = new javax.swing.JButton();
        btnCancelarRegistrarDevolucion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        panelRegistrarDevolución.setBackground(new java.awt.Color(255, 255, 255));

        lblCodigoRegistrarDevolucion.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblCodigoRegistrarDevolucion.setText("Código del prestamo:");

        btnBuscarRegistrarDevolucion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnBuscarRegistrarDevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/LUPA_.png"))); // NOI18N
        btnBuscarRegistrarDevolucion.setText("Buscar");

        lblFechaPrestamoRegistrarDevolucion.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblFechaPrestamoRegistrarDevolucion.setText("Fecha del prestamo:");

        txtFechaPrestamoRegistrarDevolucion.setEnabled(false);

        lblFechaDevolucionRegistrarDevolucion.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblFechaDevolucionRegistrarDevolucion.setText("Fecha de devolucion:");

        txtFechaDevolucionRegistrarDevolucion.setEnabled(false);

        btnLimpiarRegistrarDevolucion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLimpiarRegistrarDevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/Escoba.png"))); // NOI18N
        btnLimpiarRegistrarDevolucion.setText("Limpiar");

        lblEstadoRegistrarDevolucion.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblEstadoRegistrarDevolucion.setText("Estado:");

        txtEstadoRegistrarDevolucion.setEnabled(false);

        tblLibrosRegistrarDevolucion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLibrosRegistrarDevolucion);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Libro/s prestado/s");

        btnDevolverRegistrarDevolucion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnDevolverRegistrarDevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/dev.png"))); // NOI18N
        btnDevolverRegistrarDevolucion.setText("Devolver");

        btnCancelarRegistrarDevolucion.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCancelarRegistrarDevolucion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/X.png"))); // NOI18N
        btnCancelarRegistrarDevolucion.setText("Cancelar");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/devolucion.png"))); // NOI18N

        javax.swing.GroupLayout panelRegistrarDevoluciónLayout = new javax.swing.GroupLayout(panelRegistrarDevolución);
        panelRegistrarDevolución.setLayout(panelRegistrarDevoluciónLayout);
        panelRegistrarDevoluciónLayout.setHorizontalGroup(
            panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrarDevoluciónLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrarDevoluciónLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(166, 166, 166))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrarDevoluciónLayout.createSequentialGroup()
                            .addComponent(lblCodigoRegistrarDevolucion)
                            .addGap(257, 257, 257)))
                    .addGroup(panelRegistrarDevoluciónLayout.createSequentialGroup()
                        .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoRegistarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelRegistrarDevoluciónLayout.createSequentialGroup()
                                .addComponent(btnBuscarRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(btnLimpiarRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))))
            .addGroup(panelRegistrarDevoluciónLayout.createSequentialGroup()
                .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarDevoluciónLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(btnDevolverRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btnCancelarRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistrarDevoluciónLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEstadoRegistrarDevolucion)
                            .addComponent(lblFechaDevolucionRegistrarDevolucion)
                            .addComponent(lblFechaPrestamoRegistrarDevolucion))
                        .addGap(18, 18, 18)
                        .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFechaPrestamoRegistrarDevolucion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstadoRegistrarDevolucion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaDevolucionRegistrarDevolucion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelRegistrarDevoluciónLayout.setVerticalGroup(
            panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarDevoluciónLayout.createSequentialGroup()
                .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarDevoluciónLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblCodigoRegistrarDevolucion)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoRegistarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLimpiarRegistrarDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarRegistrarDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)))
                    .addGroup(panelRegistrarDevoluciónLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarDevoluciónLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistrarDevoluciónLayout.createSequentialGroup()
                        .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaPrestamoRegistrarDevolucion)
                            .addComponent(txtFechaPrestamoRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaDevolucionRegistrarDevolucion)
                            .addComponent(txtFechaDevolucionRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstadoRegistrarDevolucion)
                            .addComponent(txtEstadoRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)))
                .addGroup(panelRegistrarDevoluciónLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDevolverRegistrarDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarRegistrarDevolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRegistrarDevolución, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelRegistrarDevolución, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnBuscarRegistrarDevolucion() {
        return btnBuscarRegistrarDevolucion;
    }

    public void setBtnBuscarRegistrarDevolucion(JButton btnBuscarRegistrarDevolucion) {
        this.btnBuscarRegistrarDevolucion = btnBuscarRegistrarDevolucion;
    }

    public JButton getBtnCancelarRegistrarDevolucion() {
        return btnCancelarRegistrarDevolucion;
    }

    public void setBtnCancelarRegistrarDevolucion(JButton btnCancelarRegistrarDevolucion) {
        this.btnCancelarRegistrarDevolucion = btnCancelarRegistrarDevolucion;
    }

    public JButton getBtnDevolverRegistrarDevolucion() {
        return btnDevolverRegistrarDevolucion;
    }

    public void setBtnDevolverRegistrarDevolucion(JButton btnDevolverRegistrarDevolucion) {
        this.btnDevolverRegistrarDevolucion = btnDevolverRegistrarDevolucion;
    }

    public JButton getBtnLimpiarRegistrarDevolucion() {
        return btnLimpiarRegistrarDevolucion;
    }

    public void setBtnLimpiarRegistrarDevolucion(JButton btnLimpiarRegistrarDevolucion) {
        this.btnLimpiarRegistrarDevolucion = btnLimpiarRegistrarDevolucion;
    }

    public JPanel getPanelRegistrarDevolución() {
        return panelRegistrarDevolución;
    }

    public void setPanelRegistrarDevolución(JPanel panelRegistrarDevolución) {
        this.panelRegistrarDevolución = panelRegistrarDevolución;
    }

    public JTable getTblLibrosRegistrarDevolucion() {
        return tblLibrosRegistrarDevolucion;
    }

    public void setTblLibrosRegistrarDevolucion(JTable tblLibrosRegistrarDevolucion) {
        this.tblLibrosRegistrarDevolucion = tblLibrosRegistrarDevolucion;
    }

    public JTextField getTxtCodigoRegistarDevolucion() {
        return txtCodigoRegistarDevolucion;
    }

    public void setTxtCodigoRegistarDevolucion(JTextField txtCodigoRegistarDevolucion) {
        this.txtCodigoRegistarDevolucion = txtCodigoRegistarDevolucion;
    }

    public JTextField getTxtEstadoRegistrarDevolucion() {
        return txtEstadoRegistrarDevolucion;
    }

    public void setTxtEstadoRegistrarDevolucion(JTextField txtEstadoRegistrarDevolucion) {
        this.txtEstadoRegistrarDevolucion = txtEstadoRegistrarDevolucion;
    }

    public JTextField getTxtFechaDevolucionRegistrarDevolucion() {
        return txtFechaDevolucionRegistrarDevolucion;
    }

    public void setTxtFechaDevolucionRegistrarDevolucion(JTextField txtFechaDevolucionRegistrarDevolucion) {
        this.txtFechaDevolucionRegistrarDevolucion = txtFechaDevolucionRegistrarDevolucion;
    }

    public JTextField getTxtFechaPrestamoRegistrarDevolucion() {
        return txtFechaPrestamoRegistrarDevolucion;
    }

    public void setTxtFechaPrestamoRegistrarDevolucion(JTextField txtFechaPrestamoRegistrarDevolucion) {
        this.txtFechaPrestamoRegistrarDevolucion = txtFechaPrestamoRegistrarDevolucion;
    }

    public void mostarMensaje(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarRegistrarDevolucion;
    private javax.swing.JButton btnCancelarRegistrarDevolucion;
    private javax.swing.JButton btnDevolverRegistrarDevolucion;
    private javax.swing.JButton btnLimpiarRegistrarDevolucion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigoRegistrarDevolucion;
    private javax.swing.JLabel lblEstadoRegistrarDevolucion;
    private javax.swing.JLabel lblFechaDevolucionRegistrarDevolucion;
    private javax.swing.JLabel lblFechaPrestamoRegistrarDevolucion;
    private javax.swing.JPanel panelRegistrarDevolución;
    private javax.swing.JTable tblLibrosRegistrarDevolucion;
    private javax.swing.JTextField txtCodigoRegistarDevolucion;
    private javax.swing.JTextField txtEstadoRegistrarDevolucion;
    private javax.swing.JTextField txtFechaDevolucionRegistrarDevolucion;
    private javax.swing.JTextField txtFechaPrestamoRegistrarDevolucion;
    // End of variables declaration//GEN-END:variables
}
