/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class UsuarioBuscarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuarioBuscarView
     */
    public UsuarioBuscarView() {
        initComponents();
    }
    
    public void cambiarIdioma(Locale locale) {
        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);
        
        lblCedulaUsuarioBuscar.setText(bundle.getString("usuario.cedula"));
    lblNombreUsuarioBuscar.setText(bundle.getString("usuario.nombre"));
    lblTelefonoUsuarioBuscar.setText(bundle.getString("usuario.telefono"));

    btnBuscarUsuarioBuscar.setText(bundle.getString("boton.buscar"));
    btnLimpiarUsuarioBuscar.setText(bundle.getString("boton.limpiar"));
    btnCancelarUsuarioBuscar.setText(bundle.getString("boton.cancelar"));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUsuarioBuscar = new javax.swing.JPanel();
        lblNombreUsuarioBuscar = new javax.swing.JLabel();
        lblCedulaUsuarioBuscar = new javax.swing.JLabel();
        txtNombreUsuarioBuscar = new javax.swing.JTextField();
        txtCedulaUsuarioBuscar = new javax.swing.JTextField();
        btnBuscarUsuarioBuscar = new javax.swing.JButton();
        btnCancelarUsuarioBuscar = new javax.swing.JButton();
        btnLimpiarUsuarioBuscar = new javax.swing.JButton();
        lblTelefonoUsuarioBuscar = new javax.swing.JLabel();
        txtTelefonoUsuarioBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        panelUsuarioBuscar.setBackground(new java.awt.Color(204, 255, 255));

        lblNombreUsuarioBuscar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblNombreUsuarioBuscar.setText("Nombre:");

        lblCedulaUsuarioBuscar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblCedulaUsuarioBuscar.setText("Cédula:");

        txtNombreUsuarioBuscar.setEnabled(false);
        txtNombreUsuarioBuscar.addActionListener(this::txtNombreUsuarioBuscarActionPerformed);

        txtCedulaUsuarioBuscar.addActionListener(this::txtCedulaUsuarioBuscarActionPerformed);

        btnBuscarUsuarioBuscar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnBuscarUsuarioBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/LUPA_.png"))); // NOI18N
        btnBuscarUsuarioBuscar.setText("Buscar");
        btnBuscarUsuarioBuscar.addActionListener(this::btnBuscarUsuarioBuscarActionPerformed);

        btnCancelarUsuarioBuscar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCancelarUsuarioBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/X.png"))); // NOI18N
        btnCancelarUsuarioBuscar.setText("Cancelar");

        btnLimpiarUsuarioBuscar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLimpiarUsuarioBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/Escoba.png"))); // NOI18N
        btnLimpiarUsuarioBuscar.setText("Limpiar");

        lblTelefonoUsuarioBuscar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblTelefonoUsuarioBuscar.setText("Telefono:");

        txtTelefonoUsuarioBuscar.setEnabled(false);

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/buscarUsuario.png"))); // NOI18N

        javax.swing.GroupLayout panelUsuarioBuscarLayout = new javax.swing.GroupLayout(panelUsuarioBuscar);
        panelUsuarioBuscar.setLayout(panelUsuarioBuscarLayout);
        panelUsuarioBuscarLayout.setHorizontalGroup(
            panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioBuscarLayout.createSequentialGroup()
                .addGroup(panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCedulaUsuarioBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCedulaUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelUsuarioBuscarLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnBuscarUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefonoUsuarioBuscar)
                    .addComponent(lblNombreUsuarioBuscar))
                .addGap(32, 32, 32)
                .addGroup(panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTelefonoUsuarioBuscar)
                    .addComponent(txtNombreUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelarUsuarioBuscar)
                .addGap(52, 52, 52)
                .addComponent(btnLimpiarUsuarioBuscar)
                .addGap(121, 121, 121))
            .addGroup(panelUsuarioBuscarLayout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUsuarioBuscarLayout.setVerticalGroup(
            panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioBuscarLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedulaUsuarioBuscar)
                    .addComponent(lblNombreUsuarioBuscar)
                    .addComponent(txtNombreUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelefonoUsuarioBuscar)
                        .addComponent(txtTelefonoUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarUsuarioBuscar)
                    .addComponent(btnLimpiarUsuarioBuscar))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelUsuarioBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelUsuarioBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioBuscarActionPerformed

    private void txtCedulaUsuarioBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaUsuarioBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaUsuarioBuscarActionPerformed

    private void btnBuscarUsuarioBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUsuarioBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarUsuarioBuscarActionPerformed

    public JButton getBtnBuscarUsuarioBuscar() {
        return btnBuscarUsuarioBuscar;
    }

    public JButton getBtnCancelarUsuarioBuscar() {
        return btnCancelarUsuarioBuscar;
    }

    public JButton getBtnLimpiarUsuarioBuscar() {
        return btnLimpiarUsuarioBuscar;
    }

    public JTextField getTxtCedulaUsuarioBuscar() {
        return txtCedulaUsuarioBuscar;
    }

    public JTextField getTxtNombreUsuarioBuscar() {
        return txtNombreUsuarioBuscar;
    }

    public JTextField getTxtTelefonoUsuarioBuscar() {
        return txtTelefonoUsuarioBuscar;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarUsuarioBuscar;
    private javax.swing.JButton btnCancelarUsuarioBuscar;
    private javax.swing.JButton btnLimpiarUsuarioBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCedulaUsuarioBuscar;
    private javax.swing.JLabel lblNombreUsuarioBuscar;
    private javax.swing.JLabel lblTelefonoUsuarioBuscar;
    private javax.swing.JPanel panelUsuarioBuscar;
    private javax.swing.JTextField txtCedulaUsuarioBuscar;
    private javax.swing.JTextField txtNombreUsuarioBuscar;
    private javax.swing.JTextField txtTelefonoUsuarioBuscar;
    // End of variables declaration//GEN-END:variables
}
