/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

/**
 *
 * @author USER
 */
public class UsuarioBuscarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuarioBuscarView
     */
    public UsuarioBuscarView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUsuarioBuscar = new javax.swing.JPanel();
        lblNombreUsuarioBuscar = new javax.swing.JLabel();
        lblCedulaUsuarioBuscar = new javax.swing.JLabel();
        txtNombreUsuarioBuscar = new javax.swing.JTextField();
        txtCedulaUsuarioBuscar = new javax.swing.JTextField();
        btnBuscarUsuarioBuscar = new javax.swing.JButton();
        btnCancelarUsuarioBuscar = new javax.swing.JButton();
        btnLimpiarUsuarioBuscar = new javax.swing.JButton();
        lblTelefonoUsuarioBuscar = new javax.swing.JLabel();
        txtTelefonoUsuarioBuscar = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblNombreUsuarioBuscar.setText("Nombre:");

        lblCedulaUsuarioBuscar.setText("Cédula:");

        txtNombreUsuarioBuscar.setEnabled(false);
        txtNombreUsuarioBuscar.addActionListener(this::txtNombreUsuarioBuscarActionPerformed);

        txtCedulaUsuarioBuscar.addActionListener(this::txtCedulaUsuarioBuscarActionPerformed);

        btnBuscarUsuarioBuscar.setText("Buscar");

        btnCancelarUsuarioBuscar.setText("Cancelar");

        btnLimpiarUsuarioBuscar.setText("Limpiar");

        lblTelefonoUsuarioBuscar.setText("Telefono:");

        txtTelefonoUsuarioBuscar.setEnabled(false);

        javax.swing.GroupLayout panelUsuarioBuscarLayout = new javax.swing.GroupLayout(panelUsuarioBuscar);
        panelUsuarioBuscar.setLayout(panelUsuarioBuscarLayout);
        panelUsuarioBuscarLayout.setHorizontalGroup(
            panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioBuscarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuarioBuscarLayout.createSequentialGroup()
                        .addComponent(lblTelefonoUsuarioBuscar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelUsuarioBuscarLayout.createSequentialGroup()
                        .addGroup(panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreUsuarioBuscar)
                            .addComponent(lblCedulaUsuarioBuscar))
                        .addGroup(panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUsuarioBuscarLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtCedulaUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnBuscarUsuarioBuscar)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioBuscarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombreUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefonoUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
            .addGroup(panelUsuarioBuscarLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnCancelarUsuarioBuscar)
                .addGap(52, 52, 52)
                .addComponent(btnLimpiarUsuarioBuscar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelUsuarioBuscarLayout.setVerticalGroup(
            panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioBuscarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaUsuarioBuscar)
                    .addComponent(txtCedulaUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarUsuarioBuscar))
                .addGap(33, 33, 33)
                .addGroup(panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUsuarioBuscar)
                    .addComponent(txtNombreUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoUsuarioBuscar)
                    .addComponent(txtTelefonoUsuarioBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(panelUsuarioBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarUsuarioBuscar)
                    .addComponent(btnLimpiarUsuarioBuscar))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelUsuarioBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelUsuarioBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioBuscarActionPerformed

    private void txtCedulaUsuarioBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaUsuarioBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaUsuarioBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarUsuarioBuscar;
    private javax.swing.JButton btnCancelarUsuarioBuscar;
    private javax.swing.JButton btnLimpiarUsuarioBuscar;
    private javax.swing.JLabel lblCedulaUsuarioBuscar;
    private javax.swing.JLabel lblNombreUsuarioBuscar;
    private javax.swing.JLabel lblTelefonoUsuarioBuscar;
    private javax.swing.JPanel panelUsuarioBuscar;
    private javax.swing.JTextField txtCedulaUsuarioBuscar;
    private javax.swing.JTextField txtNombreUsuarioBuscar;
    private javax.swing.JTextField txtTelefonoUsuarioBuscar;
    // End of variables declaration//GEN-END:variables
}
