/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class UsuarioActualizarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuarioActualizarView
     */
    public UsuarioActualizarView() {
        initComponents();
    }
    
    public void cambiarIdioma(Locale locale) {
        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);
        
        lblCedulaUsuarioActualizar.setText(bundle.getString("usuario.cedula"));
    lblNombreUsuarioActualizar.setText(bundle.getString("usuario.nombre"));
    lblTelefonoUsuarioActualizar.setText(bundle.getString("usuario.telefono"));

    btnBuscarUsuarioActualizar.setText(bundle.getString("boton.buscar"));
    btnActualizarUsuarioActualizar.setText(bundle.getString("boton.actualizar"));
    btnLimpiarUsuarioActualizar.setText(bundle.getString("boton.limpiar"));
    btnCancelarUsuarioActualizar.setText(bundle.getString("boton.cancelar"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUsuarioActualizar = new javax.swing.JPanel();
        lblNombreUsuarioActualizar = new javax.swing.JLabel();
        lblCedulaUsuarioActualizar = new javax.swing.JLabel();
        txtNombreUsuarioActualizar = new javax.swing.JTextField();
        txtCedulaUsuarioActualizar = new javax.swing.JTextField();
        btnBuscarUsuarioActualizar = new javax.swing.JButton();
        btnCancelarUsuarioActualizar = new javax.swing.JButton();
        btnLimpiarUsuarioActualizar = new javax.swing.JButton();
        btnActualizarUsuarioActualizar = new javax.swing.JButton();
        lblTelefonoUsuarioActualizar = new javax.swing.JLabel();
        txtTelefonoUsuarioActualizar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbxCedulaUsuarioActualizar = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        panelUsuarioActualizar.setBackground(new java.awt.Color(207, 162, 124));
        panelUsuarioActualizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblNombreUsuarioActualizar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblNombreUsuarioActualizar.setText("Nombre:");

        lblCedulaUsuarioActualizar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblCedulaUsuarioActualizar.setText("Cédula:");

        txtNombreUsuarioActualizar.addActionListener(this::txtNombreUsuarioActualizarActionPerformed);

        txtCedulaUsuarioActualizar.addActionListener(this::txtCedulaUsuarioActualizarActionPerformed);

        btnBuscarUsuarioActualizar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnBuscarUsuarioActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/LUPA_.png"))); // NOI18N
        btnBuscarUsuarioActualizar.setText("Buscar");

        btnCancelarUsuarioActualizar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCancelarUsuarioActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/X-.png"))); // NOI18N
        btnCancelarUsuarioActualizar.setText("Cancelar");

        btnLimpiarUsuarioActualizar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLimpiarUsuarioActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/Escoba.png"))); // NOI18N
        btnLimpiarUsuarioActualizar.setText("Limpiar");

        btnActualizarUsuarioActualizar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnActualizarUsuarioActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/actualizarU.png"))); // NOI18N
        btnActualizarUsuarioActualizar.setText("Actualizar");

        lblTelefonoUsuarioActualizar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblTelefonoUsuarioActualizar.setText("Teléfono:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/actualizarUsuario-Photoroom.png"))); // NOI18N

        cbxCedulaUsuarioActualizar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelUsuarioActualizarLayout = new javax.swing.GroupLayout(panelUsuarioActualizar);
        panelUsuarioActualizar.setLayout(panelUsuarioActualizarLayout);
        panelUsuarioActualizarLayout.setHorizontalGroup(
            panelUsuarioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioActualizarLayout.createSequentialGroup()
                .addGroup(panelUsuarioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuarioActualizarLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblCedulaUsuarioActualizar)
                        .addGap(13, 13, 13)
                        .addGroup(panelUsuarioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedulaUsuarioActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(btnBuscarUsuarioActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addComponent(cbxCedulaUsuarioActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(panelUsuarioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUsuarioActualizarLayout.createSequentialGroup()
                                .addComponent(lblTelefonoUsuarioActualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTelefonoUsuarioActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelUsuarioActualizarLayout.createSequentialGroup()
                                .addComponent(lblNombreUsuarioActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombreUsuarioActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelUsuarioActualizarLayout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabel1))
                    .addGroup(panelUsuarioActualizarLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(btnActualizarUsuarioActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarUsuarioActualizar)
                        .addGap(27, 27, 27)
                        .addComponent(btnLimpiarUsuarioActualizar)))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        panelUsuarioActualizarLayout.setVerticalGroup(
            panelUsuarioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioActualizarLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(panelUsuarioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUsuarioActualizar)
                    .addComponent(txtNombreUsuarioActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedulaUsuarioActualizar)
                    .addComponent(txtCedulaUsuarioActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCedulaUsuarioActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUsuarioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelUsuarioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelefonoUsuarioActualizar)
                        .addComponent(txtTelefonoUsuarioActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarUsuarioActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(panelUsuarioActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizarUsuarioActualizar)
                    .addComponent(btnCancelarUsuarioActualizar)
                    .addComponent(btnLimpiarUsuarioActualizar))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelUsuarioActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelUsuarioActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActualizarActionPerformed

    private void txtCedulaUsuarioActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaUsuarioActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaUsuarioActualizarActionPerformed

    public JButton getBtnActualizarUsuarioActualizar() {
        return btnActualizarUsuarioActualizar;
    }

    public JButton getBtnBuscarUsuarioActualizar() {
        return btnBuscarUsuarioActualizar;
    }

    public JButton getBtnCancelarUsuarioActualizar() {
        return btnCancelarUsuarioActualizar;
    }

    public JButton getBtnLimpiarUsuarioActualizar() {
        return btnLimpiarUsuarioActualizar;
    }

    public JTextField getTxtCedulaUsuarioActualizar() {
        return txtCedulaUsuarioActualizar;
    }

    public JTextField getTxtNombreUsuarioActualizar() {
        return txtNombreUsuarioActualizar;
    }

    public JTextField getTxtTelefonoUsuarioActualizar() {
        return txtTelefonoUsuarioActualizar;
    }

    public JComboBox<String> getCbxCedulaUsuarioActualizar() {
        return cbxCedulaUsuarioActualizar;
    }

    public void mostarMensaje(String mensaje){
        JOptionPane.showMessageDialog(this, mensaje);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarUsuarioActualizar;
    private javax.swing.JButton btnBuscarUsuarioActualizar;
    private javax.swing.JButton btnCancelarUsuarioActualizar;
    private javax.swing.JButton btnLimpiarUsuarioActualizar;
    private javax.swing.JComboBox<String> cbxCedulaUsuarioActualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCedulaUsuarioActualizar;
    private javax.swing.JLabel lblNombreUsuarioActualizar;
    private javax.swing.JLabel lblTelefonoUsuarioActualizar;
    private javax.swing.JPanel panelUsuarioActualizar;
    private javax.swing.JTextField txtCedulaUsuarioActualizar;
    private javax.swing.JTextField txtNombreUsuarioActualizar;
    private javax.swing.JTextField txtTelefonoUsuarioActualizar;
    // End of variables declaration//GEN-END:variables
}
