/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */
public class UsuarioEliminarView extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuarioEliminarView
     */
    public UsuarioEliminarView() {
        initComponents();
    }
    
    public void cambiarIdioma(Locale locale) {
        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);
        
        lblCedulaUsuarioEliminar.setText(bundle.getString("usuario.cedula"));
    lblNombreUsuarioEliminar.setText(bundle.getString("usuario.nombre"));
    lblTelefonoUsuarioEliminar.setText(bundle.getString("usuario.telefono"));

    btnBuscarUsuarioEliminar.setText(bundle.getString("boton.buscar"));
    btnEliminarUsuarioEliminar.setText(bundle.getString("boton.eliminar"));
    btnLimpiarUsuarioEliminar.setText(bundle.getString("boton.limpiar"));
    btnCancelarUsuarioEliminar.setText(bundle.getString("boton.cancelar"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUsuarioEliminar = new javax.swing.JPanel();
        lblNombreUsuarioEliminar = new javax.swing.JLabel();
        lblCedulaUsuarioEliminar = new javax.swing.JLabel();
        txtNombreUsuarioEliminar = new javax.swing.JTextField();
        txtCedulaUsuarioEliminar = new javax.swing.JTextField();
        btnBuscarUsuarioEliminar = new javax.swing.JButton();
        btnCancelarUsuarioEliminar = new javax.swing.JButton();
        btnLimpiarUsuarioEliminar = new javax.swing.JButton();
        btnEliminarUsuarioEliminar = new javax.swing.JButton();
        lblTelefonoUsuarioEliminar = new javax.swing.JLabel();
        txtTelefonoUsuarioEliminar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        panelUsuarioEliminar.setBackground(new java.awt.Color(204, 255, 255));

        lblNombreUsuarioEliminar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblNombreUsuarioEliminar.setText("Nombre:");

        lblCedulaUsuarioEliminar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblCedulaUsuarioEliminar.setText("Cédula:");

        txtNombreUsuarioEliminar.setEnabled(false);
        txtNombreUsuarioEliminar.addActionListener(this::txtNombreUsuarioEliminarActionPerformed);

        txtCedulaUsuarioEliminar.addActionListener(this::txtCedulaUsuarioEliminarActionPerformed);

        btnBuscarUsuarioEliminar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarUsuarioEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/LUPA_.png"))); // NOI18N
        btnBuscarUsuarioEliminar.setText("Buscar");

        btnCancelarUsuarioEliminar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnCancelarUsuarioEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/X.png"))); // NOI18N
        btnCancelarUsuarioEliminar.setText("Cancelar");

        btnLimpiarUsuarioEliminar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnLimpiarUsuarioEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/Escoba.png"))); // NOI18N
        btnLimpiarUsuarioEliminar.setText("Limpiar");
        btnLimpiarUsuarioEliminar.addActionListener(this::btnLimpiarUsuarioEliminarActionPerformed);

        btnEliminarUsuarioEliminar.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnEliminarUsuarioEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/eliminar.png"))); // NOI18N
        btnEliminarUsuarioEliminar.setText("Eliminar");

        lblTelefonoUsuarioEliminar.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        lblTelefonoUsuarioEliminar.setText("Teléfono");

        txtTelefonoUsuarioEliminar.setEnabled(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/imagenes/eliminarUsuario.png"))); // NOI18N

        javax.swing.GroupLayout panelUsuarioEliminarLayout = new javax.swing.GroupLayout(panelUsuarioEliminar);
        panelUsuarioEliminar.setLayout(panelUsuarioEliminarLayout);
        panelUsuarioEliminarLayout.setHorizontalGroup(
            panelUsuarioEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioEliminarLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(btnEliminarUsuarioEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarUsuarioEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiarUsuarioEliminar)
                .addGap(0, 73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsuarioEliminarLayout.createSequentialGroup()
                .addGroup(panelUsuarioEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelUsuarioEliminarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(panelUsuarioEliminarLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnBuscarUsuarioEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTelefonoUsuarioEliminar))
                    .addGroup(panelUsuarioEliminarLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(lblCedulaUsuarioEliminar)
                        .addGap(41, 41, 41)
                        .addComponent(txtCedulaUsuarioEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreUsuarioEliminar)))
                .addGap(18, 18, 18)
                .addGroup(panelUsuarioEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreUsuarioEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                    .addComponent(txtTelefonoUsuarioEliminar))
                .addContainerGap())
        );
        panelUsuarioEliminarLayout.setVerticalGroup(
            panelUsuarioEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelUsuarioEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUsuarioEliminar)
                    .addComponent(txtNombreUsuarioEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedulaUsuarioEliminar)
                    .addComponent(txtCedulaUsuarioEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelUsuarioEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUsuarioEliminarLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(panelUsuarioEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefonoUsuarioEliminar)
                            .addComponent(txtTelefonoUsuarioEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelUsuarioEliminarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarUsuarioEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(panelUsuarioEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarUsuarioEliminar)
                    .addComponent(btnCancelarUsuarioEliminar)
                    .addComponent(btnLimpiarUsuarioEliminar))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuarioEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsuarioEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioEliminarActionPerformed

    private void txtCedulaUsuarioEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaUsuarioEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaUsuarioEliminarActionPerformed

    private void btnLimpiarUsuarioEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarUsuarioEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarUsuarioEliminarActionPerformed

    public JButton getBtnLimpiarUsuarioEliminar() {
        return btnLimpiarUsuarioEliminar;
    }
    
    
    public JButton getBtnBuscarUsuarioEliminar() {
        return btnBuscarUsuarioEliminar;
    }

    public JButton getBtnCancelarUsuarioEliminar() {
        return btnCancelarUsuarioEliminar;
    }

    public JButton getBtnEliminarUsuarioEliminar() {
        return btnEliminarUsuarioEliminar;
    }

    public JTextField getTxtCedulaUsuarioEliminar() {
        return txtCedulaUsuarioEliminar;
    }

    public JTextField getTxtNombreUsuarioEliminar() {
        return txtNombreUsuarioEliminar;
    }

    public JTextField getTxtTelefonoUsuarioEliminar() {
        return txtTelefonoUsuarioEliminar;
    }

    public int mostarMensaje(String mensaje){
        return JOptionPane.showConfirmDialog(this, mensaje);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarUsuarioEliminar;
    private javax.swing.JButton btnCancelarUsuarioEliminar;
    private javax.swing.JButton btnEliminarUsuarioEliminar;
    private javax.swing.JButton btnLimpiarUsuarioEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCedulaUsuarioEliminar;
    private javax.swing.JLabel lblNombreUsuarioEliminar;
    private javax.swing.JLabel lblTelefonoUsuarioEliminar;
    private javax.swing.JPanel panelUsuarioEliminar;
    private javax.swing.JTextField txtCedulaUsuarioEliminar;
    private javax.swing.JTextField txtNombreUsuarioEliminar;
    private javax.swing.JTextField txtTelefonoUsuarioEliminar;
    // End of variables declaration//GEN-END:variables
}
