/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

import ec.edu.ups.biblioteca.models.Usuario;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class UsuarioListarView extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo2;
    private String nombre;
    private String cedula;
    private String telefono;

    /**
     * Creates new form UsuarioListarView
     */
    public UsuarioListarView() {
        initComponents();
        cambiarIdioma(new Locale("es","EC"));
        configurarTabla();
    }
    public void cambiarIdioma(Locale locale){
        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes",locale);
        nombre = bundle.getString("keyNombre");
        cedula = bundle.getString("keyCedula");
        telefono = bundle.getString("keyTelefono");
        
         if (modelo2 != null) {
        modelo2.setColumnIdentifiers(new Object[]{nombre, cedula, telefono});
    }
    }

    public void configurarTabla() {
        modelo2 = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        modelo2.addColumn(nombre);
        modelo2.addColumn(cedula);
        modelo2.addColumn(telefono);

        tblUsuarioListar.setModel(modelo2);

        tblUsuarioListar.getTableHeader().setReorderingAllowed(false);
        tblUsuarioListar.getTableHeader().setResizingAllowed(false);
    }

    public void cargarDatos(List<Usuario> usuarios) {

        modelo2.setRowCount(0);

        for (Usuario usuario : usuarios) {
            Object[] fila = {usuario.getNombre(), usuario.getCedula(), usuario.getNumero()};
            modelo2.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarioListar = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblUsuarioListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarioListar.setEnabled(false);
        jScrollPane1.setViewportView(tblUsuarioListar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarioListar;
    // End of variables declaration//GEN-END:variables
}
