/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.biblioteca.view;

/**
 *
 * @author USER
 */
public class UsuarioCrearView extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuarioCrearView
     */
    public UsuarioCrearView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUsuarioCrear = new javax.swing.JPanel();
        lblNombreUsuarioCrear = new javax.swing.JLabel();
        lblCedulaUsuarioCrear = new javax.swing.JLabel();
        txtNombreUsuarioCrear = new javax.swing.JTextField();
        txtCedulaUsuarioCrear = new javax.swing.JTextField();
        btnCrearUsuarioCrear = new javax.swing.JButton();
        btnCancelarUsuarioCrear = new javax.swing.JButton();
        btnLimpiarUsuarioCrear = new javax.swing.JButton();
        lblTelefonoUsuarioCrear = new javax.swing.JLabel();
        txtTelefonoUsuarioCrear = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblNombreUsuarioCrear.setText("Nombre:");

        lblCedulaUsuarioCrear.setText("Cédula:");

        txtNombreUsuarioCrear.addActionListener(this::txtNombreUsuarioCrearActionPerformed);

        txtCedulaUsuarioCrear.addActionListener(this::txtCedulaUsuarioCrearActionPerformed);

        btnCrearUsuarioCrear.setText("Crear");

        btnCancelarUsuarioCrear.setText("Cancelar");

        btnLimpiarUsuarioCrear.setText("Limpiar");

        lblTelefonoUsuarioCrear.setText("Teléfono:");

        txtTelefonoUsuarioCrear.addActionListener(this::txtTelefonoUsuarioCrearActionPerformed);

        javax.swing.GroupLayout panelUsuarioCrearLayout = new javax.swing.GroupLayout(panelUsuarioCrear);
        panelUsuarioCrear.setLayout(panelUsuarioCrearLayout);
        panelUsuarioCrearLayout.setHorizontalGroup(
            panelUsuarioCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioCrearLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelUsuarioCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreUsuarioCrear)
                    .addComponent(lblTelefonoUsuarioCrear)
                    .addComponent(lblCedulaUsuarioCrear))
                .addGap(18, 18, 18)
                .addGroup(panelUsuarioCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreUsuarioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelUsuarioCrearLayout.createSequentialGroup()
                        .addComponent(btnCrearUsuarioCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarUsuarioCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiarUsuarioCrear))
                    .addGroup(panelUsuarioCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTelefonoUsuarioCrear, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCedulaUsuarioCrear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelUsuarioCrearLayout.setVerticalGroup(
            panelUsuarioCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioCrearLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelUsuarioCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreUsuarioCrear)
                    .addComponent(txtNombreUsuarioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelUsuarioCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaUsuarioCrear)
                    .addComponent(txtCedulaUsuarioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUsuarioCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonoUsuarioCrear)
                    .addComponent(txtTelefonoUsuarioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelUsuarioCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearUsuarioCrear)
                    .addComponent(btnCancelarUsuarioCrear)
                    .addComponent(btnLimpiarUsuarioCrear))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelUsuarioCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelUsuarioCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioCrearActionPerformed

    private void txtCedulaUsuarioCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaUsuarioCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaUsuarioCrearActionPerformed

    private void txtTelefonoUsuarioCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoUsuarioCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoUsuarioCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarUsuarioCrear;
    private javax.swing.JButton btnCrearUsuarioCrear;
    private javax.swing.JButton btnLimpiarUsuarioCrear;
    private javax.swing.JLabel lblCedulaUsuarioCrear;
    private javax.swing.JLabel lblNombreUsuarioCrear;
    private javax.swing.JLabel lblTelefonoUsuarioCrear;
    private javax.swing.JPanel panelUsuarioCrear;
    private javax.swing.JTextField txtCedulaUsuarioCrear;
    private javax.swing.JTextField txtNombreUsuarioCrear;
    private javax.swing.JTextField txtTelefonoUsuarioCrear;
    // End of variables declaration//GEN-END:variables
}
